### ISSUE TITLE
[BUG] 'Use Invidious instead of Youtube' breaks Youtube playback

### ISSUE THREAD

**Issue by terabyte3** [Moosync/Moosync#103]
**Describe the bug**
After enabling the 'Use Invidious instead of Youtube' option in System settings, Youtube playback completely stops working. Spotify playback DOES still work.

**To Reproduce**

1. Go to 'Settings'
2. Click on the 'System' tab
3. Select 'Use Invidious instead of Youtube'
4. Try playing a song from Youtube.

**Expected behavior**
The expected behavior is for the song to play.

- OS: Windows 11 21H2
- Version v4.0.0

**Additional context**
The logs talk about ETIMEDOUT, UnhandledPromiseRejectionWarning, and getaddrinfo ENOTFOUND v.

**Comment by Ovenoboyo** [comment]
Thank you for reporting this bug. I'll take a look at it

**Comment by Ovenoboyo** [comment]
May i know which invidious instance are you using?

**Comment by terabyte3** [comment]
I've tried multiple, but the main one that I use is https://vid.puffyan.us

**Comment by Ovenoboyo** [comment]
Can you check if the same song you're trying to play is playable on that invidious instance? Cause for me it happens at times watching from an instance outside my country gives me some errors

**Comment by Ovenoboyo** [comment]
There is also an ongoing issue over at invidious which i believe might be related to this
https://github.com/iv-org/invidious/issues/92

**Comment by Ovenoboyo** [comment]
@terabyte3 Can you try a build from the below link?
https://github.com/Moosync/Moosync/suites/7165820756/artifacts/285459746

**Comment by terabyte3** [comment]
It looks like this may have been something else, as Invidious playback just started working again. I'm still not sure what originally caused the issue, because I had tried multiple instances and none of them worked, so I don't believe it was a instance issue.

**Comment by Ovenoboyo** [comment]
Haha glad to hear that it's working again. Though you might have helped to solve a completely unrelated problem then. Thank again for that. I'll be closing this PR now :)
