### ISSUE TITLE
[BUG] Youtube features completely break after relinking account

### ISSUE THREAD

**Issue by halworsen** [Moosync/Moosync#104]
**Describe the bug**
The Youtube features broke completely after attempting to re-connect to my Youtube account. None of the Youtube features seem to be working anymore. Tried relinking through both the browser links and the code. Also tried manually removing moosync's access to my account before relinking.

**To Reproduce**
Unsure if this is 100% reproducible, but:

1. Link a YT account
2. Unlink the account
3. Should no longer be able to use YT search or link a new YT account

**Expected behavior**
Linking to my account is not actually that important to me, but it would be nice to keep the search at least.

- OS: Manjaro Linux 5.16.18-1
- Moosync version: 4.0.0

**Additional context**
Enabled debug logs, but nothing pops up after a search.
Immediately after attempting to link my YT account:
![image](https://user-images.githubusercontent.com/9088854/177016682-a6ba9726-86e4-4e81-b9e2-f4484f6430e8.png)

**Comment by halworsen** [comment]
Unsure what happened overnight but it all suddenly works now. Maybe something on YT's end/weird network issues?

**Comment by Ovenoboyo** [comment]
> Unsure what happened overnight but it all suddenly works now. Maybe something on YT's end/weird network issues?

It is quite possible. Anyways glad that it's working now. I'll be closing the issue but feel free to comment on it if you start facing the problem again.
