### ISSUE TITLE
Spotify Login Redirect URI

### ISSUE THREAD

**Issue by Krishna-bansall** [Moosync/Moosync#116]
**Describe the bug**
Spotify Login Redirect is shown as invalid after creating an application from spotify 

**To Reproduce**

1. Install Moosync through pacman 
3. Do Beginner Setup
4. Connect with Spotify automatically
5. See error

**Expected behavior**
Application was supposed to be redirected to moosync home page and auth in with spotify
**Screenshots**
![image](https://user-images.githubusercontent.com/69707056/184396864-1ce4ff30-03a0-403e-9df1-3c79cc49e56d.png)
![image](https://user-images.githubusercontent.com/69707056/184397465-2dd2e7c1-7f5b-4639-a922-fc06a68f0da1.png)

- OS: Arch Linux (Manjaro)
- Version [5.15.59-1-MANJARO]

**Additional context**
The most probable issue is the link has expired for spotify because youtube and lastfm are working just fine

**Comment by Ovenoboyo** [comment]
Head over to (https://developer.spotify.com/dashboard/) and login using your Spotify credentials. After logging in you should be able to see a card named "Moosync". Open that and press on "Edit Settings" in top right. Inside that there should be a section called as "Redirect URIs". Could you tell me the entries inside that section?

**Comment by Krishna-bansall** [comment]
Redirect URI - https://moosync.app/spotifyhttp://localhost

**Comment by Ovenoboyo** [comment]
Could you try to make it so that it matches the screenshot?

![image](https://user-images.githubusercontent.com/36789504/184476396-1baf8bbe-e2d2-45cb-bdb8-67542b245591.png)

**Comment by Krishna-bansall** [comment]
Yeah that works

**Comment by IllNoobis** [comment]
This is happening with me, I fixxed this but **after it** whenever I 
![image](https://github.com/user-attachments/assets/e140c7f6-0028-433e-81b1-59608dd5fac0)
Nothing happenes after I click this button, it goes back but it stil shows:
![image](https://github.com/user-attachments/assets/ac81a4ab-c037-4c35-8825-31e69ca1813c)

**Comment by Ovenoboyo** [comment]
Can you try to see if there is anything relevant under settings > logs after you enter the code?

**Comment by IllNoobis** [comment]
Not sure if they're related but there's a hell of these:
![image](https://github.com/user-attachments/assets/bfe1ae45-06d0-4944-a78f-083adc564f66)
From when I was trying to login to spotify. :/

**Comment by IllNoobis** [comment]
Also is there a folder where log files are stored. txt format or what ever so I can just send directly?
