### ISSUE TITLE
[BUG] Music will not play in Win 11

### ISSUE THREAD

**Issue by owopi** [Moosync/Moosync#119]
**Describe the bug**
No music will play from any sources and the queue is blank (it is an empty screen).

**To Reproduce**
I downloaded it, linked my Youtube and Spotify and it worked for a week or so and it stopped working after a restart.

**Expected behavior**
For it to play music.

**Screenshots**
![image](https://user-images.githubusercontent.com/95185333/186284306-33b2e3b4-bca2-442b-9a01-552ae72186c4.png)
Image of the error in logs

- OS: Windows 11
- Version: 4.0.0

**Additional context**
Tried uninstalling and reinstalling and deleting folder in program files, still had issue when reinstalled. 

Edit: It works with version 3.0.1 when installing with chocolatey, but not the .exe from releases.

**Comment by Ovenoboyo** [comment]
Can you try to remove the folder in 
```C:\users\<your_username>\AppData\Roaming\moosync```
And see if it works?

**Comment by owopi** [comment]
It works, just misclicked, thanks for the help!

**Comment by owopi** [comment]
It works; thanks for the help! (misclicked and forgot comment)

**Comment by Ovenoboyo** [comment]
Don't worry, glad I could help :)
