### ISSUE TITLE
[FEATURE] Media player controls

### ISSUE THREAD

**Issue by angelobreuer** [Moosync/Moosync#124]
**Is your feature request related to a problem? Please describe.**

I really like the tiny media player controls in Windows, when you hover over an app. Unfortunately, this feature is missing in Moosync.

**Describe the solution you'd like**

Media player controls like:

![image](https://user-images.githubusercontent.com/46497296/188801172-cc2aaaa6-1838-4aac-a0b2-ac23a7521aee.png)
(Windows 11, when you hover over a media player in the taskbar)

**Describe alternatives you've considered**
- None

**Additional context**

The keyboard hotkeys already work for pausing, skipping, and replaying a track.

**Comment by Ovenoboyo** [comment]
![unknown](https://user-images.githubusercontent.com/36789504/190462847-7f346520-5bdd-474a-9b0f-949782a4281f.png)

I've added buttons like this. Should be available from the next release

**Comment by angelobreuer** [comment]
Wow! Thank you 🎉
