### ISSUE TITLE
[FEATURE] user script support

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [Moosync/Moosync#128]
**Is your feature request related to a problem? Please describe.**
Moosync stops playing music when it tries to play an age restricted video and loads forever.

**Describe the solution you'd like**
User script support, so you can add scripts like simple YouTube age restriction bypass

**Describe alternatives you've considered**
Inbuilt age restriction bypass on YouTube

**Additional context**
![image](https://user-images.githubusercontent.com/88291316/191310561-fae02893-6c9d-4c79-af44-4c458fc1f71d.png)

**Comment by Ovenoboyo** [comment]
Could you link to at age restriction bypass script. I've been meaning to find one but couldn't.

**Comment by Ovenoboyo** [comment]
I'm moving the age restriction to a new issue. Lets track it at #130

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Is implemented :)
