### ISSUE TITLE
[BUG]Youtube channel wont sign in on linux

### ISSUE THREAD

**Issue by The-Purge-King** [Moosync/Moosync#129]
So i follow the process carefully trying to connect my youtube account on the app after i noticed that for some reason it wasnt connected while working fine before sometime but no matter how many times i tried while everything seems to be going fine i cant manage to connect it in the app. If anyone has any suggestions on how to solve this issue i would appreciate it!
Thank you for your time

**Comment by Ovenoboyo** [comment]
The API key for YouTube I had been using has been revoked due to violations of their service policy. I'll need to find an alternative for it but till then features like YouTube login, User playlists, playlist search, artist search won't work. A temporary solution would be to manually search your songs. 

Sorry for the inconvenience

**Comment by The-Purge-King** [comment]
> 

Oh dont worry about it. Take all the time you time you need i was just worrying that i did something wrong so i came here to see if that was the case. I am loving the app so i can wait as long as it takes :p

**Comment by Ovenoboyo** [comment]
[v5.1.0](https://github.com/Moosync/Moosync/releases/tag/v5.1.0) should require you to enter your own client_id and client_secret for Youtube just like how it was done for Spotify. The process to get them has been documented [here](https://moosync.app/wiki/integrations#enabling-youtube-integration). 

However logging in to Youtube is not required to use the features of Youtube. Logging in will only show your own playlists under the "Playlists" section of the app. You may manually add your playlists by URL without logging in by right-clicking in the "Playlists" section and selecting "Add playlists from URL" (The playlist must be unlisted or public).

I'm closing this issue for now. Feel free to reopen this issue if you have any questions or just drop a message on discord :)

**Comment by The-Purge-King** [comment]
Understood everything clearly. :D
Thank you so much for your fast and detailed solution to my issue!!!
I appreciate all of your effort and i am excited to keep on using the app regularly😊
