### ISSUE TITLE
[FEATURE] Multimedia options in Moosync Tray

### ISSUE THREAD

**Issue by Terkyz** [Moosync/Moosync#132]
**Is your feature request related to a problem? Please describe.**
More or less. Add a facility for the user to change the song without having to open the Tray application, change the song and close it again.

**Describe the solution you'd like**
Right click on the Moosync Tray icon with options for next, pause, previous, etc.

**Describe alternatives you've considered**
Hotkeys on the multimedia keys of the keyboard, although I don't know if this is already in development or if it fulfills the same function.

**Additional context**
ඞ.

**Comment by Ovenoboyo** [comment]
![image](https://user-images.githubusercontent.com/36789504/192161254-bb0765cd-2774-45e4-901f-e830d98110f1.png)

Here's how the new tray should look. I'm closing this issue, if it does not fit your requirement feel free to reopen it :)

**Comment by Terkyz** [comment]
I have been using these functions and they are great, but isn't the option to pause the music also needed?

> ![image](https://user-images.githubusercontent.com/36789504/192161254-bb0765cd-2774-45e4-901f-e830d98110f1.png)
> 
> Here's how the new tray should look. I'm closing this issue, if it does not fit your requirement feel free to reopen it :)

**Comment by Ovenoboyo** [comment]
Play and pause should toggle with the state of the player. If the song is current playing, a pause button would show up and vice versa.

Let me know if it isn't working as expected
