### ISSUE TITLE
[FEATURE] Online Radio Station Player

### ISSUE THREAD

**Issue by Terkyz** [Moosync/Moosync#133]
**Is your feature request related to a problem? Please describe.**
No. A music player that uses online radio stations, I got tired of how bad [Shortwave ](https://www.omgubuntu.co.uk/2020/03/shortwave-radio-player-linux) sometimes is.

**Describe the solution you'd like**
An integrated online radio player option, with a list of "most listened to" radios and online radio search capabilities

**Describe alternatives you've considered**
I have been using Shortwave for months but it is insufferable that it doesn't even have basic capabilities like right-click bookmarking.

**Additional context**
This is a mere suggestion, if this is too difficult to implement or it deviates from the philosophy of "Music Player" it is not necessary to add it.

**Comment by Ovenoboyo** [comment]
I do feel like it deviates a bit from the concept of a Music player but it shouldn't be a problem implementing it. So I thought it would be better to implement this feature separately as an extension in a different [repository](https://github.com/Ovenoboyo/moosync_radio_provider). When its completed, it should be available under Settings > Extensions > Discover

**Comment by Ovenoboyo** [comment]
I've published an initial build for the radio extension. 

For now you get "Top 100 stations" as a playlist and you can search and add stations to your library as well. 

Search also has special filters like tag, codec, state, country, name, language. For eg. If you want to search for stations in **Austria**, you could search for the term **"country:austria"**. [I'll document this somewhere properly later]

**Comment by Terkyz** [comment]
> I've published an initial build for the radio extension.
> 
> For now you get "Top 100 stations" as a playlist and you can search and add stations to your library as well.
> 
> Search also has special filters like tag, codec, state, country, name, language. For eg. If you want to search for stations in **Austria**, you could search for the term **"country:austria"**. [I'll document this somewhere properly later]

It works exceptionally well, I love having the ability to search for random music when I can't think of what to listen to (which is more common than it should be).

**Comment by t3dium** [comment]
Yeah this extension is great, never really listened to radio before lol, moosync got me into it now though.
