### ISSUE TITLE
[feature] enabling proxying over invidious

### ISSUE THREAD

**Issue by t3dium** [Moosync/Moosync#134]
since moosync supports invidious could proxying over invidious also be enabled/an option? to prevent sending queries to google directly.

also, i've noticed google video domains popping up in my dns logs when playing spotify songs, does moosync get spotify song names and get it from youtube? if so, could that also go over invidious?

incredible app btw, looks and works very well

**Comment by Ovenoboyo** [comment]
Do you mean proxying the video through Invidious' servers like mentioned [here](https://docs.invidious.io/proxy-videos/) or through a custom external proxy?

And yes you're right, Moosync does indeed play a Spotify song through Youtube. If Invidious is enabled and configured, the search process should happen over invidious. I'll look into why it isn't working this way.

Also I'm glad the you liked the app

**Comment by t3dium** [comment]
> Do you mean proxying the video through Invidious' servers like mentioned [here](https://docs.invidious.io/proxy-videos/) or through a custom external proxy?

proxying through invidious's servers yeah, not all instances have the option available, but for those which do it'd generally increase privacy.

**Comment by Ovenoboyo** [comment]
> proxying through invidious's servers yeah, not all instances have the option available, but for those which do it'd generally increase privacy.

Oh ok that makes sense. The app already proxies some videos if they are geo-blocked on google video domain. So implementing it for all videos shouldn't be a problem

**Comment by Ovenoboyo** [comment]
@t3dium Do you know of any instance which does not support proxying?

**Comment by t3dium** [comment]
> @t3dium Do you know of any instance which does not support proxying?

https://invidious.tiekoetter.com, https://inv.privacy.com.de/, https://invidious.nerdvpn.de have the option grayed out 
![image](https://user-images.githubusercontent.com/83690012/194752522-12cbf34c-a301-4fab-a9bf-9524d488b171.png)

aside from those 3, all the others on the official instance list have the option available

**Comment by Ovenoboyo** [comment]
Thanks for helping. I've added an option which to proxy songs from Invdious under Settings > System. It should be visible starting next update and should be turned on by default. If you don't want to wait for the next release, you may use the build from [here](https://github.com/Moosync/Moosync/actions/workflows/build.yml) (You might need to login to Github to download releases)

**Comment by t3dium** [comment]
> Thanks for helping. I've added an option which to proxy songs from Invdious under Settings > System. It should be visible starting next update and should be turned on by default. If you don't want to wait for the next release, you may use the build from [here](https://github.com/Moosync/Moosync/actions/workflows/build.yml) (You might need to login to Github to download releases)

Works perfectly, thanks
