### ISSUE TITLE
[feature] publish on scoop extras repository

### ISSUE THREAD

**Issue by t3dium** [Moosync/Moosync#136]
better than chocolately for a windows package manager, moosync should also fit its criteria as it has more than 100 stars 

https://github.com/ScoopInstaller/Scoop for the package manager

https://github.com/ScoopInstaller/Extras for the official repository

**Comment by Ovenoboyo** [comment]
Oh this seems cool. I've never personally used Scoop but I'll definitely look into it.

**Comment by Ovenoboyo** [comment]
Hey, thanks for showing interest. I've been quite busy a few days and gotta admit the development has slowed down.

If you could work on the package manifest that would help a lot

**Comment by EmirLogas** [comment]
It would be nice to have a Scoop package. I support this feature.

**Comment by aliesbelik** [comment]
PR with manifest for `extras` bucket submitted [here](ScoopInstaller/Extras#12401).
Tests, review or comments will be helpful.

**Comment by aliesbelik** [comment]
> The link gives 404 error?

Fixed.
Sorry, my fault with link formatting.

**Comment by aliesbelik** [comment]
Merged.

```
scoop bucket add extras
scoop install moosync
```
