### ISSUE TITLE
[feature] piped support (invidious but with playlist, artist and album support)

### ISSUE THREAD

**Issue by t3dium** [Moosync/Moosync#139]
[Piped](https://github.com/TeamPiped/Piped) is similar to invidious but allows searching for artists, playlists and albums

the api for piped is here: https://piped-docs.kavin.rocks/docs/api-documentation/

**Comment by Ovenoboyo** [comment]
Ah this looks pretty cool. I'll take a look at this

**Comment by t3dium** [comment]
the latest piped commit results in songs infinitely loading, tried using a couple different instances but same issue

**Comment by Ovenoboyo** [comment]
> the latest piped commit results in songs infinitely loading (only when using the piped option), tried using a couple different instances but same issue

Ah Thanks for letting me know... I'll check

**Comment by Ovenoboyo** [comment]
@t3dium it seems to be working properly for me... Could you link me to few songs to try? It would also be helpful if you could mention your piped instance URL and the commit hash you're on.

**Comment by t3dium** [comment]
> @t3dium it seems to be working properly for me... Could you link me to few songs to try? It would also be helpful if you could mention your piped instance URL and the commit hash you're on.

i now tried #143 and it appears to have been fixed, playing songs and searching for playlists/albums/songs works. 

However there's a minor bug with the large thumbnails being low resolution/blurry when using piped.

![image](https://user-images.githubusercontent.com/83690012/196225406-3415fb7b-d3c2-4dec-af0c-17aae66ea021.png)


theres also a bug where some search terms for channels don't return any results (e.g, lyrical lemonade or LYRICAL LEMONADE gets stuck on loading), however when pasting the playlist id (which i got from my browser https://piped.kavin.rocks/playlist?list=PLfvpqdsXvlf4vqsRWglvSPplpKkEsBI7E)   -->  (PLfvpqdsXvlf4vqsRWglvSPplpKkEsBI7E)    it returns results, in the playlists section

search term word directly
![image](https://user-images.githubusercontent.com/83690012/196229493-be1e0f42-18bc-4a33-881c-ebed603f4c7d.png)

playlist id however works
![image](https://user-images.githubusercontent.com/83690012/196228325-91ab9107-4249-450a-b966-b0e85c71c8a9.png)
 

tried with the kavin.rocks instance, privacy.com.de and garudalinux

other than that, everything else works perfectly

**Comment by Ovenoboyo** [comment]
For playlist search, i am making use of music_playlist filter which I believe returns only the playlists from YouTube music (I'm not sure how they are categorised).

 I could make it such that if no playlists are found with that filter, it would fallback to normal YouTube playlists.

Or do you think simply getting playlists from normal YouTube would be a better option?

**Comment by Ovenoboyo** [comment]
Also maybe the reason for playlists not loading was something different. I noticed that sometimes the uploaderUrl of a video returned from pipe was null (idk how). It should be fixed in https://github.com/Moosync/Moosync/commit/a1c34fd23ae76b0bd15d9726d9d6dc6dc536ee58

**Comment by t3dium** [comment]
> For playlist search, i am making use of music_playlist filter which I believe returns only the playlists from YouTube music (I'm not sure how they are categorised).
> 
> I could make it such that if no playlists are found with that filter, it would fallback to normal YouTube playlists.
> 
> Or do you think simply getting playlists from normal YouTube would be a better option?

if possible could there be a seperate search with (non music) youtube button? 

maybe having it use youtube music first, but having a button in the bottom right corner which when clicked does the same search but on normal youtube (not music).

alternatively, i think the fallback option is also good

**Comment by Ovenoboyo** [comment]
> > For playlist search, i am making use of music_playlist filter which I believe returns only the playlists from YouTube music (I'm not sure how they are categorised).
> > I could make it such that if no playlists are found with that filter, it would fallback to normal YouTube playlists.
> > Or do you think simply getting playlists from normal YouTube would be a better option?
> 
> if possible could there be a seperate search with (non music) youtube button?
> 
> maybe having it use youtube music first, but having a button in the bottom right corner which when clicked does the same search but on normal youtube (not music).
> 
> alternatively, i think the fallback option is also good

Adding this would be a inconsistency between all the Youtube alternatives as well as other providers which I'd like to avoid. IMO a better option would be to simply use playlists from normal Youtube and just forget about Youtube music playlists. Since I believe that playlists from normal Youtube should also contain results from Youtube music.

**Comment by t3dium** [comment]
new commit works great, searching "lyrical lemonade" with piped now returns playlist results
