### ISSUE TITLE
[feature] saving spotify/youtube/piped playlists which update whenever new songs are added in the playlist tab

### ISSUE THREAD

**Issue by t3dium** [Moosync/Moosync#144]
It’d be nice to be able to add playlists directly from moosync and have them update with new songs for spotify and youtube/piped.

**Comment by Ovenoboyo** [comment]
Sorry I didn't quite understand what you meant. 

Do you want to sync playlists such that whenever you add a song to a Spotify playlist in Moosync, that song should also be added to your Spotify playlist on Spotify.com? [And similar for Youtube and Piped]

**Comment by t3dium** [comment]
> Sorry I didn't quite understand what you meant.
> 
> Do you want to sync playlists such that whenever you add a song to a Spotify playlist in Moosync, that song should also be added to your Spotify playlist on Spotify.com? [And similar for Youtube and Piped]

I meant having a “save” option when searching for playlists on moosync, and also having it update as opposed to only saving songs which were in the playlist at the time

**Comment by Ovenoboyo** [comment]
Ah ok, this seems doable

**Comment by t3dium** [comment]
works great thanks
