### ISSUE TITLE
[FEATURE] Icons on tray menu

### ISSUE THREAD

**Issue by SonGokussj4** [Moosync/Moosync#155]
Current tray menu looks lonely. Some icons before text would be helpful :-)

Current:
![image](https://user-images.githubusercontent.com/13331858/198216446-1ca9309b-13ce-4aaf-9d6b-8fb82509ba97.png)

Clementine:
![image](https://user-images.githubusercontent.com/13331858/198216614-2538e369-e840-4404-8da6-e1e15e89e840.png)

**Comment by Ovenoboyo** [comment]
I've tried to add icons for both light and dark themes but the detection by electron for dark mode seems unstable to me. It does not work properly in KDE (Not sure if its my setup or just electron in general and I haven't tried any other DE). It does work on Windows.

**Comment by t3dium** [comment]
looks great
