### ISSUE TITLE
Not all songs are showing in spotify playlists

### ISSUE THREAD

**Issue by Menorah** [Moosync/Moosync#161]
**Describe the bug**
Not all songs are showing in spotify playlists

**To Reproduce**
When I choose a playlist, only part of the added songs are visible. For example, in this [playlist](https://open.spotify.com/playlist/2ADXzKaLi8UGqJlEOq7FNy?si=0d5fb10f69634830) of over 140 tracks, only the first 100 are shown.

- OS: Windows 11

**Comment by Ovenoboyo** [comment]
The songs are lazy loaded, meaning only 100 songs will be fetched from Spotify at a time. If you scroll down to the bottom of the list, it should start loading the next 100 songs. Let me know if this isn't working.

**Comment by Menorah** [comment]
> The songs are lazy loaded, meaning only 100 songs will be fetched from Spotify at a time. If you scroll down to the bottom of the list, it should start loading the next 100 songs. Let me know if this isn't working.

I think I found the problem. When I set the song list appearance to classic mode, the player does not load the entire list.

**Comment by Ovenoboyo** [comment]
Ohh I see, I'll fix that. Thanks for figuring it out

**Comment by Ovenoboyo** [comment]
I'll be closing this issue since it seems to be fixed. Feel free to reopen it if you feel otherwise.
