### ISSUE TITLE
;[FEATURE] Turn the sound up and down using the mouse wheel 

### ISSUE THREAD

**Issue by Terkyz** [Moosync/Moosync#162]
**Is your feature request related to a problem? Please describe.**
No. But it is a gesture that other music players (and other programs, such as Youtube) have, and there may be many people used to it.

**Describe the solution you'd like**
When placing the mouse over the volume bar, if I move the lever forward the audio increases and if I move it backward it decreases.

**Describe alternatives you've considered**
I don't know...

**Additional context**
[Add any other context or screenshots about the feature request here.](https://imgur.com/tD1V3Im)

**Comment by Ovenoboyo** [comment]
Yeah this sounds cool and convenient... I'll work on it

**Comment by Ovenoboyo** [comment]
I'll be closing this issue since it seems to be fixed. Feel free to reopen it if you feel otherwise.
