### ISSUE TITLE
[BUG] Songs with filename with "." (dot) in it, get their name cut.

### ISSUE THREAD

**Issue by Ybaedbaenn** [Moosync/Moosync#165]
**Describe the bug**
When a song has a dot (".") in it's filename, the part of the name after the dot is cut out.

**To Reproduce**
Install Moosync 6.0.0
Add a song from file with name like "author ft. co-author - name.mp3" to the queue
Check that the displayed name is "author ft"
Compare to files without dot in their name, those display correctly

**Expected behavior**
The full name of the song is displayed, only the file extension gets cut out.

**Screenshots**
![image](https://user-images.githubusercontent.com/84321760/199344401-8d8a85ea-27a1-4511-ba0e-eac238a0e705.png)

- OS: Windows 10 Home
- Version: 6.0.0

**Additional context**
I had been using a previous version of Moosync, uninstalled it with "Uninstall Moosync.exe" and installed the version 6.0.0, the bug still remains, so I'm not sure if I upgraded the program correctly.
I have tested both 3 letter (.mp3) and 4 letter (.opus) file extensions, and the bug occurs in each case.

**Comment by Ybaedbaenn** [comment]
The same thing happens on a openSUSE Tumbleweed 20220921 clean install.

**Comment by Ybaedbaenn** [comment]
I can also confirm that the bug exists on Windows 11 Pro 10.0.22000

**Comment by Ovenoboyo** [comment]
Thanks for reporting it. I'll look into it

**Comment by Ybaedbaenn** [comment]
Yes, I can confirm I'm on 6.0.0. I used the AppImage version on a newly installed openSUSE machine. Here is a video of the bug being reproduced on Windows 10. It does appear in queue and some other places, I haven't tested it everywhere.


https://user-images.githubusercontent.com/84321760/199559431-80823ae9-91bc-40a5-a5d5-45ed133a9b20.mp4

**Comment by Ovenoboyo** [comment]
My bad, I'd completely forgotten about the "drag to play song" feature. I'll fix this behaviour

**Comment by Ybaedbaenn** [comment]
Thanks!

**Comment by Ovenoboyo** [comment]
I'll be closing this issue since it seems to be fixed. Feel free to reopen it if you feel otherwise.
