### ISSUE TITLE
[FEATURE] Default search from invidious, not local.

### ISSUE THREAD

**Issue by GitHubWhatsup** [Moosync/Moosync#172]
I only use this app for invidious. It's kind of annoying that I need to click "Invidious" after searching.

**Comment by Ovenoboyo** [comment]
Thats fair. I could make it such that it remembers your last selection. So for you it will default to Invidious if you don't use anything. Does this work?

**Comment by Ovenoboyo** [comment]
I'll be closing this issue since it seems to be fixed. Feel free to reopen it if you feel otherwise.
