### ISSUE TITLE
Double clicking on a Mp3 file doesnt play[BUG]

### ISSUE THREAD

**Issue by mahmutelmas06** [Moosync/Moosync#175]
**Describe the bug**
If you double click to a mp3 file or with Open With... action, music doenst play. 

**To Reproduce**

1. Go to click to a mp3 file
2. moosync starts
3. No error, just main screen appears.

**Expected behavior**
Playing the mp3 file i clicked on.

- OS: [e.g. Linux]
Windows 10

**Comment by Ovenoboyo** [comment]
Thank you for reporting this bug. Could you check if dragging that MP3 file from file explorer onto Moosync plays the song or not?

**Comment by mahmutelmas06** [comment]
Yes is does play the song very well if i drag into

**Comment by Ovenoboyo** [comment]
I see, thanks I'll check it out.

**Comment by Ovenoboyo** [comment]
I'll be closing this issue since it seems to be fixed. Feel free to reopen it if you feel otherwise.
