### ISSUE TITLE
[FEATURE] Queue improvement

### ISSUE THREAD

**Issue by Konglomneshued** [Moosync/Moosync#177]
**Is your feature request related to a problem? Please describe.**
Yes, the queue is really unintuitive.  I have to queue a song and then play it.  I also have to clear it every time I finish listening to a song, otherwise when I queue a playlist, random songs not in it will start playing because they're still in the queue.

**Describe the solution you'd like**
Songs should be removed from the queue once they finish or stop playing.

**Additional context**
The app is bugging out for me again, so I have to post this and restart before grabbing screenshots.

**Comment by Ovenoboyo** [comment]
Your points do make sense but not everyone prefers having old songs removed when queuing a new playlist. Instead what I could do is provide a configurable option whether to clear the queue or now.

Also what kind of bugs are we talking about?

**Comment by Konglomneshued** [comment]
Hi, thank you for getting back to me.

What I mean by bug was when I click the app icon to launch it, it doesn't launch.  I have to click it again or maybe a few more times.

Also, sometimes it doesn't play any audio, or maybe the slider never moves but the queue shows it's playing with an animation.

Sorry that I forgot to grab screenshots.

**Comment by Ovenoboyo** [comment]
Ahh I see. Your first issue is probably related to #164. If you don't want to wait for the next release you may get the CI build which contains the fixes for that issue at https://github.com/Moosync/Moosync/actions/runs/3670194404.

**Comment by Ovenoboyo** [comment]
I'll be closing this issue since it seems to be fixed. Feel free to reopen it if you feel otherwise.
