### ISSUE TITLE
[BUG] Piped Login Not Working

### ISSUE THREAD

**Issue by Fero337** [Moosync/Moosync#182]
When trying to link my Piped account to MooSync, i get the message "Are you sure you want to signout from Piped?
Press Confirm if you are sure" even though I've never logged in before. Restarting/Resetting the program won't help here.

**Comment by Ovenoboyo** [comment]
Hey, first of all thank you for using the app. As of this moment, login using piped is not really supported. To view your piped playlists in the app, you'll have to add them manually. This can be done by right clicking anywhere in the playlist's tab and selecting "Add playlist from URL" or just searching the playlist URL. 

I'll definitely consider adding account support for piped though.

**Comment by candroid-man** [comment]
There is a great project you could utilize called Hyperpipe ([official instance](https://hyperpipe.surge.sh/) and [source code](https://codeberg.org/Hyperpipe/Hyperpipe)), which uses Piped to fetch YouTube Music. Integrating Hyperpipe would be the easiest to integrate since it is all there already (unless I'm wrong, not a programmer)

**Comment by Ovenoboyo** [comment]
Oh I see. I'll definitely look into it

**Comment by Ovenoboyo** [comment]
@candroid-man I was looking into Hyperpipe but it seems that it also does not offer the functionality to login to a piped instance or did I miss something?

**Comment by candroid-man** [comment]
Hah, yeah it took me a while to find too. You can login, it is near the bottom of the page if I recall

**Comment by Ovenoboyo** [comment]
Oh yeah found it. Its in the library tab

**Comment by Ovenoboyo** [comment]
I'll be closing this issue since it seems to be fixed. Feel free to reopen it if you feel otherwise.
