### ISSUE TITLE
Moosync not starting

### ISSUE THREAD

**Issue by Six-Elements** [Moosync/Moosync#183]
No working version from v1.0.0 to 6.0.0

![1111](https://user-images.githubusercontent.com/73589161/207424123-af2e4fda-b0c3-4a7c-9862-d5600cf9680e.jpg)

Window 10  22H2

**Comment by Ovenoboyo** [comment]
Hey thanks for reporting this bug, could you try the build from https://github.com/Moosync/Moosync/actions/runs/3688018815. You'll need to login to Github before you can download the build. You can scroll down on that page to find the builds. Click on "windows exe" (or whichever one suits you) to start the download.

**Comment by Ovenoboyo** [comment]
Seems similar to #164

**Comment by Six-Elements** [comment]
The new version also comes with a bug

![1111](https://user-images.githubusercontent.com/73589161/207437201-a1e7e677-bd3b-4d6c-a774-0806e80e6dcc.jpg)

**Comment by Ovenoboyo** [comment]
I see. Sorry for the inconvenience ,I'll look into this

**Comment by Six-Elements** [comment]
Thank you the last version works great

![11](https://user-images.githubusercontent.com/73589161/207654112-313760fc-088f-46da-81c0-282da010afec.jpg)

[https://github.com/Moosync/Moosync/actions/runs/3695037363](url)

**Comment by Ovenoboyo** [comment]
Hey, sorry for the late reply but could you try the build at https://github.com/Moosync/Moosync/actions/runs/3717393738?

**Comment by Ovenoboyo** [comment]
I'll be closing this issue since it seems to be fixed. Feel free to reopen it if you feel otherwise.
