### ISSUE TITLE
[BUG] Media key for Play/Pause is not working

### ISSUE THREAD

**Issue by Soncomander** [Moosync/Moosync#184]
**Describe the bug**
**Next**, **Prev** and **Stop** media keys are working, but **Play/Pause** is not working, regardless of playback status.

In other programs all keys are working correctly.

**To Reproduce**

1. Open moosync
2. Add some music to the queue and play it
3. Test all media keys, all should work expect **Play/Pause**

**Expected behavior**
Switch between Play and Pause in playback.

- OS: Ubuntu 20.04.5 LTS
- Version: Moosync 6.0.0 (APT)

**Comment by Ovenoboyo** [comment]
Coincidentally I fixed this issue in 7d8c26d37caea82d8b902a2ddc8667063b997da4 but I haven't got a chance to test it out yet. Could you try the build from https://github.com/Moosync/Moosync/actions/runs/3695037363 and see if it works?

**Comment by Soncomander** [comment]
Nice! Yep, worked!
I tested the AppImage and the .deb package, both worked.

**Comment by Ovenoboyo** [comment]
Great, glad it works

**Comment by Ovenoboyo** [comment]
I'll be closing this issue since it seems to be fixed. Feel free to reopen it if you feel otherwise.
