### ISSUE TITLE
[FEATURE] Option to customize the characters used to split the artists

### ISSUE THREAD

**Issue by uKaigo** [Moosync/Moosync#186]
**Is your feature request related to a problem? Please describe.**
I think it is. Right now artist names are split every `&`, `,` and `;` (probably more, but didn't look into it).
This causes a problem where artists have these characters in their name, for example "Earth, Wind & Fire" turns into "Earth, Fire, Wind" - 3 separate artists.

**Describe the solution you'd like**
I'd like to be able to configure which characters are used to split the artist name, for example, be able to use only ";". Or at least be able to disable this behavior.

**Describe alternatives you've considered**
Sorry, but I couldn't think about an alternative to this.

**Comment by Ovenoboyo** [comment]
Ah yes this makes sense. Didn't consider that artist names could also contain a comma. I'll try to implement this

**Comment by uKaigo** [comment]
Cool, thank you
