### ISSUE TITLE
[FEATURE] Sort by track number

### ISSUE THREAD

**Issue by mattencius** [Moosync/Moosync#187]
**Is your feature request related to a problem? Please describe.**
I think so, some local songs appear out of order when adding them. It only happens when there are ten or more songs in an album and only if the first nine songs do not start with a zero in their filenames. None of the current sort options help, I tried the "Sort by date added" one but they still appear out of order. 

**Describe the solution you'd like**
I was thinking to go into every single album I own and rename the songs filenames where required to (it would take a while because there are a lot of album songs that I would have to rename, but it's doable). However, it would be nice for the future to have an option to sort by track number, at least on the albums tab.

**Describe alternatives you've considered**
I couldn't think of anything else honestly, maybe to find a way to fix it so it shows them in order whether there is a zero or not at the beginning of the filename.

**Additional context**
English is not my first language, so sorry if I didn't make myself clear 🙏

**Comment by Ovenoboyo** [comment]
So I've added an album sort option, which will sort the tracks first by their album names and then by their track numbers. Before this commit, the app did not store track numbers at all. For it to work, you'll probably have to remove all paths in settings and add them again (Un-ticking, scanning and re-ticking them again should also work).

I'll try to do a release this week with this feature but if you don't wish to wait, you can get the CI build from https://github.com/Moosync/Moosync/actions/runs/3800987251 (You'll need to be logged in to github to be able to  download it)

**Comment by mattencius** [comment]
That's wonderful news! I downloaded the CI build, and after following your instructions I can see that now it works as intended, thank you so much!
