### ISSUE TITLE
Subsonic API request

### ISSUE THREAD

**Issue by AvMavs** [Moosync/Moosync#189]
**Is your feature request related to a problem? Please describe.**
No, it's an enhancement. I want another source of media as well.

**Describe the solution you'd like**
I'd love support for the Subsonic API, so that we can use self-hosted music streaming instances like [Navidrome](https://github.com/navidrome/navidrome) or any similar server applications!

**Describe alternatives you've considered**
I currently use Sonixd, but it'd be great to have my lossless self-hosted collection on the app, similar to YT/Spotify who provide lossy audio.

**Comment by Ovenoboyo** [comment]
I've started working on it at [Subsonic Extension](https://github.com/Ovenoboyo/moosync_subsonic) but due to a few bugs in v6.0.0...v7.0.0, it won't work on those versions. I'll soon be releasing an update fixing those bugs and adding the above extension to the official repository.

**Comment by AvMavs** [comment]
Thank you very much!

**Comment by Ovenoboyo** [comment]
I've pushed v7.1.0 and [Subsonic integration for Moosync](https://github.com/Ovenoboyo/moosync_subsonic). You can find it in Settings > Extensions > Discover
