### ISSUE TITLE
[BUG] App won't open on linux

### ISSUE THREAD

**Issue by HiddenLeveI** [Moosync/Moosync#192]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

- OS: [e.g. Linux]
- Version [e.g. v0.0.8]

**Additional context**

Just downloaded the newest update for 1/1/23 on Linux and now the app won't open.

**Comment by Ovenoboyo** [comment]
Hey, thanks for reporting. I'll need some additional context like which linux distribution are you using and how did you install the app.

Could you also start the app by running ```DEBUG_LOGGING=true moosync``` in the terminal and see if there is any error?

**Comment by Terkyz** [comment]
Same exact problem, KDE Neon 22.10, Snap, Flatpak and Appimage all the same problem and that is that [this](https://i.imgur.com/5cEetZI.png) window opens and nothing else happens.

[These](https://i.imgur.com/BANA9JM.png) are the logs, same exact problem as with flatpak version

**Comment by Ovenoboyo** [comment]
> Same exact problem, KDE Neon 22.10, Snap, Flatpak and Appimage all the same problem and that is that [this](https://i.imgur.com/5cEetZI.png) window opens and nothing else happens.
> 
> [These](https://i.imgur.com/BANA9JM.png) are the logs, same exact problem as with flatpak version

Thanks for the logs, I'll have a look at them

**Comment by Ovenoboyo** [comment]
By any chance, are you on wayland?

**Comment by Terkyz** [comment]
That's right, in fact I forgot to mention it.

**Comment by Ovenoboyo** [comment]
The AppImage and Snap are missing a few dependencies and Flatpak has a broken build script which is why all 3 of them weren't working. I've updated Flatpak (might take some time to be reflected) and AppImage (updated in github releases section) so far. I'm yet to figure out the fix for Snap

**Comment by Ovenoboyo** [comment]
I believe this has been resolved now. Feel free to reopen this issue if you feel otherwise.
