### ISSUE TITLE
[BUG] AUR

### ISSUE THREAD

**Issue by Rustmilian** [Moosync/Moosync#193]
**Describe the bug**
When rust package installed the builder tries to build with it (multiple time at once too) causing higher cpu use.

**To Reproduce**
```
# Paru is an AUR helper
paru -S rust moosync
```
Use system monitor to see processes (sort by cpu use)
In the terminal once you see :
```
warning "bootstrap-vue > bootstrap@4.6.2" has unmet peer dependency "jquery@1.9.1 - 3".
[4/4] Building fresh packages...
```
You should see (multiple?) cargo processes then multiple rustc processes.
it takes 10x longer if not more to build.

**Expected behavior**
As rust is not listed as a dependence or optional dependence in the BUILDPKG, I'd expect it to not interact with the rust package at any point during build.

- OS: Arch Linux (KDE Plasma 5.26.5)
- Version v7.0.0
![1](https://user-images.githubusercontent.com/110098609/211042951-3bad29ef-5aee-454d-8251-6535c814c3f8.png)
![2](https://user-images.githubusercontent.com/110098609/211042957-982dffb0-b458-41b1-8b32-a3f2f958351d.png)

**Comment by Ovenoboyo** [comment]
Thanks for reporting. The rust dependency was added recently so I must have forgotten to add it to the AUR package.

**Comment by Rustmilian** [comment]
> Thanks for reporting. The rust dependency was added recently so I must have forgotten to add it to the AUR package.

Are the rust parts building in debug mode? If so then that may explain the excessive jump in compile time.

**Comment by Ovenoboyo** [comment]
I don't think so thats the case. Librespot by itself is a heavy dependency, maybe its why its taking so long

**Comment by Ovenoboyo** [comment]
As per the build command, [here](https://github.com/Moosync/librespot-node/blob/main/package.json#L10), ```--release``` should be passed to cargo which by default should produce an optimized build with no debug info

**Comment by Ovenoboyo** [comment]
I've updated the dependencies on both [moosync](https://aur.archlinux.org/packages/moosync) and [moosync-git](https://aur.archlinux.org/packages/moosync-git). It seems thats rustc being spawned with high CPU is normal for [librespot](https://github.com/librespot-org/librespot). 

Native module dependencies are usually compiled twice, once when installing all the dependencies and once when packaging with electron. For rust, the second compilation should take a few seconds since most targets should be cached by then.

If you'd not prefer long build times, I could provide a moosync-bin which would contain a prebuilt binary of moosync (It would however not use your system's electron binary)

**Comment by Rustmilian** [comment]
> I've updated the dependencies on both [moosync](https://aur.archlinux.org/packages/moosync) and [moosync-git](https://aur.archlinux.org/packages/moosync-git). It seems thats rustc being spawned with high CPU is normal for [librespot](https://github.com/librespot-org/librespot).
> 
> Native module dependencies are usually compiled twice, once when installing all the dependencies and once when packaging with electron. For rust, the second compilation should take a few seconds since most targets should be cached by then.
> 
> If you'd not prefer long build times, I could provide a moosync-bin which would contain a prebuilt binary of moosync (It would however not use your system's electron binary)

Thank you for updating the BUILDPKGs.
A moosync-bin would be perfect, I'm completely fine with it not using my systems electron. Only other application on my system that uses electron is discord and it uses its own electron too (tho I suppose I could be using [this](https://aur.archlinux.org/packages/discord-electron-bin) or an alternative) so I see no harm because I'll have 2 version of electron either way.
If it's possible to make the -bin version use the system electron that'd be preferable, but it's not a big deal. Thanks again.

**Comment by Ovenoboyo** [comment]
I've pushed a [moosync-bin](https://aur.archlinux.org/packages/moosync-bin) package on aur. Using system's electron was not possible since there are a few native modules which need to be compiled each time the electron version changes (This process takes 90% of the build time).

**Comment by Rustmilian** [comment]
> I've pushed a [moosync-bin](https://aur.archlinux.org/packages/moosync-bin) package on aur. Using system's electron was not possible since there are a few native modules which need to be compiled each time the electron version changes (This process takes 90% of the build time).

Thank you, I'm going to close this now.
