### ISSUE TITLE
[FEATURE] More theme customization

### ISSUE THREAD

**Issue by Zinvoke** [Moosync/Moosync#196]
Would be great if we could get the option to inject custom css for further theming I love electron apps specifically because the majority you can customize everything about them as you can see the fonts are a little too large other then that I love this app.
![xDXweTmOHp](https://user-images.githubusercontent.com/84819317/211414846-3981427e-b24c-497e-b555-f9276b219688.png)

**Comment by Ovenoboyo** [comment]
Ahh custom CSS injection would be a great thing to do. Do you know of any other app I could use as a reference point while implementing this?

**Comment by Ovenoboyo** [comment]
Also, just out of curiosity, which OS are you using

**Comment by Zinvoke** [comment]
The operating system is Windows 11 and some references:
https://github.com/be5invis/vscode-custom-css (I use this for custom vs code css)
https://betterdiscord.app (I'm sure you know what this is supports custom css)
https://github.com/vercel/hyper (Allows custom css)
From what I take you inject css into the shadow dom? I don't tinker with web languages much

**Comment by duckworx** [comment]
> Also, just out of curiosity, which OS are you usin

> 

can you give me your bd theme sir?

**Comment by Ovenoboyo** [comment]
> The operating system is Windows 11 and some references:
> https://github.com/be5invis/vscode-custom-css (I use this for custom vs code css)
> https://betterdiscord.app (I'm sure you know what this is supports custom css)
> https://github.com/vercel/hyper (Allows custom css)
> From what I take you inject css into the shadow dom? I don't tinker with web languages much

Thanks a lot. Your system looks amazing btw. I never knew you could customize windows to such an extent.

**Comment by Zinvoke** [comment]
> > The operating system is Windows 11 and some references:
> > https://github.com/be5invis/vscode-custom-css (I use this for custom vs code css)
> > https://betterdiscord.app (I'm sure you know what this is supports custom css)
> > https://github.com/vercel/hyper (Allows custom css)
> > From what I take you inject css into the shadow dom? I don't tinker with web languages much
> 
> Thanks a lot. Your system looks amazing btw. I never knew you could customize windows to such an extent.

Thank you and haha I get that alot I'm just a ricing fanatic
