### ISSUE TITLE
[BUG] App not launching on linux

### ISSUE THREAD

**Issue by felanmalan** [Moosync/Moosync#202]
**Describe the bug**
When i try to install the app, either with yay or snap, i receive an error message instead of the application launching.

Snap:
![Skärmbild från 2023-01-21 17-47-51](https://user-images.githubusercontent.com/118014695/213877591-eca95914-0875-4610-bb07-0e137055c56a.png)

AUR:
![Skärmbild från 2023-01-21 17-55-20](https://user-images.githubusercontent.com/118014695/213877896-46e802c9-76f0-48f7-9bd3-25316ef4ce92.png)

Install the package from yay with yay -S moosync (or snap)
Try to open the binary
Get error message

- OS: Arcolinux
- Version: 7.1.0-1

**Comment by Ovenoboyo** [comment]
I'm not sure why exactly MPRIS failed to register on distros like Arco or Gentoo but handling this error should be fairly simple

**Comment by Ovenoboyo** [comment]
The [moosync-git AUR package](https://aur.archlinux.org/packages/moosync-git) should contain the fixes for this bug. Could you try using it to see if its been fixed?

**Comment by IntoTheVoid-900** [comment]
The Flatpak version is working well for me (on VanillaOS). Try it out
