### ISSUE TITLE
Option for adding song in different playlist in spotify section 

### ISSUE THREAD

**Issue by expandpi** [Moosync/Moosync#209]
**Is your feature request related to a problem? Please describe.**
Is it possible to add a spotify song to different playlist. When I right click on any song then  hover to add to playlist then the adding to other created playlist is not showing. Only 2 option is there "Create Playlist and favourite". 

**Describe the solution you'd like**
When any person right click on any song and hover to Add to Playlist then all custom create playlist other could be a good idea there.

I am talking about part related to spotify here.
And thanks for this awesome app. Better than spotify for sure. Love it

**Comment by Ovenoboyo** [comment]
Thanks for reporting this. Adding a song to any playlist should be possible. I believe this should be marked as a bug

**Comment by expandpi** [comment]
I didnt get your last question. I created some playlist in spotify app but now I m not using spotify anymore and playlist created by spotify official app is there but when i right click on any song then there is no option for adding it to playlist created by official spotify app.

**Comment by Ovenoboyo** [comment]
Ah I understand what you mean now. Unfortunately the playlists you create on other platforms (Spotify, YouTube, etc) are read-only. This means that you cannot edit them inside moosync.

To add your songs, you'll have to create a new playlist inside the app itself (from the plus icon in the playlists tab). 

There is already an existing issue open regarding this #203.

**Comment by expandpi** [comment]
Ok. thanks for the clarification.
