### ISSUE TITLE
[BUG] Wrong artist name

### ISSUE THREAD

**Issue by alessandrococco** [Moosync/Moosync#210]
**Describe the bug**

Hello! I'm trying Moosync, it seems a nice app 😄 

I noticed some name-related issues:

1. I have some albums by [SednA](https://linktr.ee/_sedna). In my files the artist name is `SednA` but Moosync displays it as `Sedn A`.
2. Moosync displays `La Morte Viene Dallo Spazio` but the value in my tags is `La morte viene dallo spazio` (I think the app changes all the artists to Upper Camel Case: all `of` are now `Of`, etc...)

**Expected behavior**

1. The artist name must remain `SednA`.
2. The artist name case must not be changed

**Screenshots**

![image](https://user-images.githubusercontent.com/2331798/222776398-fa17a8b6-4532-46c5-a368-e58e177eded1.png)
(The name is wrong and consequently the photo is too.)

![image](https://user-images.githubusercontent.com/2331798/222781225-9653fa09-cb36-495d-b83b-63a23c7eca96.png)

![image](https://user-images.githubusercontent.com/2331798/222780916-bd8f6e53-ada5-4659-9265-c080fa918578.png)

![image](https://user-images.githubusercontent.com/2331798/222781124-06a21012-a769-4bf8-9f73-8658b6979a2b.png)

- OS: Win10
- Version 7.1.0

**Comment by Ovenoboyo** [comment]
Hey, thanks for reporting this bug. You're right about the capitalisation of the artist's name. I'll fix that.

Although I'm not sure why SednA is being displayed as Sedn A. I'll have to further investigate this.

**Comment by PercyPanleo** [comment]
Is it possible that the metadata on local files is getting replaced with online metadata in Moosync?

**Comment by Ovenoboyo** [comment]
I doubt that's the case. We only fetch online metadata if there is no existing one. The issue with SednA could probably be some sort of word splitting
