### ISSUE TITLE
[BUG] Few Songs don't play.

### ISSUE THREAD

**Issue by T1CkShot** [Moosync/Moosync#211]
**Describe the bug**
Some songs don't play. When play is clicked it will load up the song image and everything but it will not play. If I click to play another song (another one that doesn't play) then the screen flickers between two song pages.

**To Reproduce**
1. Playing the songs: - "Unstopabble" or "Play with fire". from this [playlist](https://open.spotify.com/playlist/61x5ZfHRCaE1D5F2u1xbYu?si=28b4831f584d4d47)

2. Play another of the mentioned song.

**Expected behavior**
The songs playing.

**Screenshots**
![image](https://user-images.githubusercontent.com/36645221/223787886-58a7c9dd-11ec-43af-8c67-bad16aaca3dd.png)

- OS: Windows 11
- Version 7.1.0

**Additional context**
----

**Comment by T1CkShot** [comment]
Apparently a lot more songs don't play. The flicker occurs because of the song getting skipped to one which is also unplayable thus getting into a loop. The lyrics and everything loads fine just the songs don't play.

**Comment by T1CkShot** [comment]
Few days alter some of the songs are playing. Without any actions taken that is. This could possibly be because of captcha.

**Comment by Ovenoboyo** [comment]
Sorry was busy for few days. Its quite possible it was due to captcha or some other kind of limitation. You could try using invidious or piped in settings > system. Maybe it could fix this issue for you. 

Or if you have a Spotify premium account, you could use librespot in settings > system. This would enable native spotify playback. (I've had reports that librespot is broken for some people but its still worth a try)

**Comment by T1CkShot** [comment]
Unfortunately the same issue persists. Although I wasn't able to  test the librespot option.

**Comment by Ovenoboyo** [comment]
Hey, would it be possible for you to try out one of the development builds from [here](https://github.com/Moosync/Moosync/actions/runs/4461104922) (You'll need to scroll down to find the download links for your OS)? There have been a few changes since 7.1.0 which could fix your particular issue.

**Comment by T1CkShot** [comment]
Thank you 8.1.0 fixed the issue.
