### ISSUE TITLE
[BUG] Freeze of 7 seconds when playing a, yet unplayed, song with a local playlist

### ISSUE THREAD

**Issue by Phibonacci** [Moosync/Moosync#213]
**Describe the bug**
With a playlist of 370 songs (360 FLAC, 9 MP3, 1 ogg/opus) Moosync freezes for 7 seconds each time I switch to a new song.

**To Reproduce**

1. Create a playlist with local files
2. Click on next, the app will freeze for 7 seconds or so
3. Directly click on next again
4. The next song will play once the app is responding again

However clicking previous then next again will not freeze the app as the song has already been played once.

**Expected behavior**
I expected to be able to skip multiple songs in a row, especially when going blind with the media key.

- OS: Windows 10
- CPU: AMD Ryzen 7 3700X
- Version: 7.1.0

**Comment by Ovenoboyo** [comment]
Hey, sorry for the late reply. Looks like I had overlooked this issue. 

I'm not able to replicate this issue unfortunately. Skipping songs seems to be working fine for me without any kind of delay (I tried with a combination of FLACs, mp3s and oggs). 

Could you try to see if this issue still persists with a [recent development build](https://github.com/Moosync/Moosync/actions/runs/4461104922)? You'll need to scroll to the bottom of the page to find download links for Windows.

**Comment by Phibonacci** [comment]
No problem at all.

I can happily confirm the issue is gone with the development build you linked.
