### ISSUE TITLE
moosync-bin for AUR repo not working

### ISSUE THREAD

**Issue by folfgirl** [Moosync/Moosync#215]
I was installing moosync and after installing I get this when executed 
" /opt/Moosync/moosync: error while loading shared libraries: libavcodec.so.59: cannot open shared object file: No such file or directory "

**To Reproduce**

install moosync-bin in the AUR 
execute moosync
" /opt/Moosync/moosync: error while loading shared libraries: libavcodec.so.59: cannot open shared object file: No such file or directory "

**Expected behavior**
I was expecting it to open moosync

- OS: arch linux
- Version 6.2.8-arch1-1

**Screen shot**
![2023-03-27_15-03](https://user-images.githubusercontent.com/79891947/228053811-fb18566c-d354-482d-941e-1086e91457da.png)

**Comment by Ovenoboyo** [comment]
Thanks for reporting this. Looks like ffmpeg bumped their libavcodec version. To fix this you'll need to install

https://aur.archlinux.org/packages/ffmpeg-compat-59

This should provide you with the missing library. Let me know if you face any issue after this

**Comment by folfgirl** [comment]
that was the first thing i tried to do it didn't work
![2023-03-28_06-57](https://user-images.githubusercontent.com/79891947/228228805-1c7867b7-ec75-468a-bb35-01a842bb7c66.png)

**Comment by folfgirl** [comment]
that was the first thing i tried to do it didn't work
![2023-03-28_06-57](https://user-images.githubusercontent.com/79891947/228228805-1c7867b7-ec75-468a-bb35-01a842bb7c66.png)

**Comment by Ovenoboyo** [comment]
Ah looks like an error with ffmpeg-compat-59. There seems to be a comment on its AUR page on how you could fix it. You could try to see if that helps.

Otherwise there seems to be a package called [moosync-appimage](https://aur.archlinux.org/packages/moosync-appimage). While its not the same thing as moosync-bin, if you don't have any problems with appimage, you could try that out.

**Comment by Ovenoboyo** [comment]
As a long term solution, I think I'll probably setup a new CI pipeline that builds non-debian packages on a newer linux distro so we're up to date on packages. I'll also keep the old pipeline on ubuntu 20.04 to support older distros as well.

**Comment by folfgirl** [comment]
ok thanks, I will keep an eye on the aur package for updates and here as while.
