### ISSUE TITLE
Song from Spotify playing without the vocals

### ISSUE THREAD

**Issue by AkiyamaMizuki3** [Moosync/Moosync#216]
**Describe the bug**
Certain song ([link](https://open.spotify.com/track/1OTkrip8I6EW5ap78axkyg?si=ead5e2bb39814283)) plays without vocals inside the app, although in Spotify it plays as normal.

**To Reproduce**

1. Open song from [link](https://open.spotify.com/track/1OTkrip8I6EW5ap78axkyg?si=ead5e2bb39814283) inside the app by any way.
2. Listen to it inside the app, listen to it inside the Spotify, notice the difference.

**Expected behavior**
I expected to hear normal version of song, not instumental version only. 

- OS: Windows 10
- System version: 21H2
- App version: v7.1.0

**Additional context**
If necessary, I can provide video with this problem, my actions, etc.
To addiction, I'm not sure that it is the only song that has such problem, but I still have not found other, thereforce I apologize in advance if the problem is on my side only.

**Comment by Ovenoboyo** [comment]
I think this is related to #73. Could you try the solution posted there to see if it helps?

**Comment by AkiyamaMizuki3** [comment]
The problem resolved itself without my intervention after a while. I think there was some rare glitch. Anyway, thanks for the answer!
