### ISSUE TITLE
Some minor improvements ideas

### ISSUE THREAD

**Issue by AkiyamaMizuki3** [Moosync/Moosync#217]
I just wanted to give some ideas of new features:
1. Open original song (in browser by link or program) from youtube/spotify/etc. by clicking on its icon on the song playbar.
2. Third option of cycle playback - play only one song while toggled (even if there is more than one song in queue).

And not so minor, but also (if its possible): 
1. Add posibility to set image as background inside the app.
2. Alpha channel in themes colors of them not working right now (its always being setted up to max value, even if it was setted to zero before), thereforce add posibility to set it to custom value.

**Comment by Ovenoboyo** [comment]
Hey, these ideas sound really cool. I'd love to implement them.

However I didn't quite understand the second point. Does the repeat button not satisfy this problem? Or perhaps I misunderstood something.

As for custom backgrounds, there should be a custom CSS theme implementation coming next update (#196). That should allow you to make any kind of modifications to the UI

**Comment by AkiyamaMizuki3** [comment]
Oh yes, the repeat button is completely satisfying, I misunderstood its functionality at the time of writing, I'm sorry

**Comment by Ovenoboyo** [comment]
I've added an option in the song's context menu to open it in your browser instead of clicking on the icon. Hope that works :)
