### ISSUE TITLE
[BUG] Top song in Explore table doesn't play when click on it

### ISSUE THREAD

**Issue by AkiyamaMizuki3** [Moosync/Moosync#218]
**Describe the bug**
Top 1 song by playtime in Explore table doesn't play when click on it.

**To Reproduce**
1. Go to Explore table
2. Click on the top 1 song by playtime in the tab (it doesn't play).
3. Besides, other songs from the top play.

**Expected behavior**
Song should appear in the playbar and start playing.

- OS: Windows 10
- Version 21H2

**Additional context**
Video: https://user-images.githubusercontent.com/67781417/230736493-e8f236e0-11d2-417a-9cc1-9432f9c632b5.mp4

**Comment by Ovenoboyo** [comment]
Should be fixed with 8.0.0 :)
