### ISSUE TITLE
[BUG] Song Custom Info & Added Playlists Dissapearing

### ISSUE THREAD

**Issue by The64thGamer** [Moosync/Moosync#222]
**Describe the bug**
If local songs are stored on an external hard-drive, and Moosync is booted up when they're unplugged, the songs will forever disappear from playlists even once plugged back in and restarted. If the songs had custom titles, descriptions, and thumbnails too, these will be erased as well. This does not affect Albums, Artists, Genres, or viewing all songs.

**To Reproduce**

1. Add songs from a local external hard drive to a playlist
2. Close out of Moosync
3. Unplug the external device
4. Reopen Moosync, playlist will be empty with '0 Songs' listed.
5. Close Moosync again
6. Replug in the harddrive
7. Open Moosync again, playlists are still empty despite paths now being accessible again. 

(Re-adding the external hard-drive path in the Song Directories also does nothing, as its still correctly loaded for non-playlist sections of the app)

**Expected behavior**
Even if a path is no longer available to read from when loading a playlist, it shouldn't delete the song from that playlist forever. At most this should just be a button in the settings menu if a user wishes to clear out a deleted songs cache.

- OS: Windows 11
- Version 7.1.0 x64

**Comment by Ovenoboyo** [comment]
I think this is expected behavior. There is an automated scan that runs every 30mins or so which would clear any songs that don't exist in the filesystem. Perhaps the solution to this issue would be to allow setting a user-defined timer to run the scan-job (In your case, perhaps disabling it would help)
