### ISSUE TITLE
[FEATURE] Adding some kind of feedback (or at least a warning) when trying to add big Music Folders

### ISSUE THREAD

**Issue by CaptainCoward** [Moosync/Moosync#228]
So i wanted to test out Moosync (it's the first time i'm, using it). I have like 7000+ Songs, sorted in different Folders like

D:/Musicfolder/R/Ramones - Album

I selected D:/Musicfolder as  Song Directory (on the first time Setup) and Moosync would get pretty unresponsive.. I figured it would just take a bit till all the songs are found. However it was so "bad" that i just gave up at some point thinking something is wrong and closed Moosync. I then tried it again leaving it running this time and after a while all the songs got added. 

However i'd suggest some kind of progress bar or  something so that the user knows the Tool is still going. Even if it is just a warning when trying to add big folders could help so that the user knows this is "normal". It just would feel much better to know what's going on instead of wondering why moosync acts unresponsive and laggy. 
I know there is a bar if you check settings/paths but when setting the music folder the first time you wouldn't see that.

It's just some feedback i wanted to give as a first time user. :)

**Comment by Ovenoboyo** [comment]
Hey, thanks for reporting this. I'd like to also add a BUG label to this issue since the app shouldn't become unresponsive even if the directory has a lot of songs.

**Comment by Ovenoboyo** [comment]
Could you also tell me what version of the app are you on?

**Comment by CaptainCoward** [comment]
It's 8.1.1

**Comment by Ovenoboyo** [comment]
Yup, tested this on my windows system and the UI does indeed become sluggish. Guess I'll need to setup an option to throttle the scan

**Comment by Ovenoboyo** [comment]
Hi, sorry for the delay but this should be fixed in v9.0.0+. I'm closing this issue since it seems to be fixed, feel free to open it if you feel otherwise :)
