### ISSUE TITLE
Play button should play songs immediately

### ISSUE THREAD

**Issue by Ovenoboyo** [Moosync/Moosync#23]
**Describe the change**
When the play button is pressed after hovering on small cover arts, it adds the song to queue instead of playing it immediately.

**What should be the actual outcome**
Song should be played immediately on pressing the play button on album arts.

**Comment by abhishek7997** [comment]
Hi!
I would like to try solving this issue.
So, please assign this issue to me.

**Comment by Ovenoboyo** [comment]
Sure go ahead

**Comment by abhishek7997** [comment]
I am not able to re-create the issue. Can you please send a video demonstrating the issue ?

**Comment by abhishek7997** [comment]
Please give me more time.

**Comment by Ovenoboyo** [comment]
> Please give me more time.

Yeah sure no problem

**Comment by Ovenoboyo** [comment]
Fixed in 8ebed82d836adb93e17b397ece02ac3123e71b86
