### ISSUE TITLE
[BUG] Not download artwork to .thumbnails folder

### ISSUE THREAD

**Issue by hrqmonteiro** [Moosync/Moosync#230]
**Describe the bug**
None of the artists/albuns are downloading any artwork.

There are even some on the .thumbnails folder, but it doesn't reflect on the app

**To Reproduce**
It is just not downloading artwork...

**Expected behavior**
To properly download them.

**Screenshots**
[Screencast from 2023-05-02 16-12-03.webm](https://user-images.githubusercontent.com/17055027/235762974-84100042-bc28-4d3a-a54a-6e64b03689db.webm)
![image](https://user-images.githubusercontent.com/17055027/235763038-6999d1ff-7c13-45a4-830c-27297ead7835.png)

- OS: [e.g. Linux]
- Fedora 38

**Additional context**
N/A

**Comment by Ovenoboyo** [comment]
Hey thanks for reporting this. I'll be sure to look at whats causing this

**Comment by Ovenoboyo** [comment]
Hi, sorry for the delay but this should be fixed in v9.0.0+. I'm closing this issue since it seems to be fixed, feel free to open it if you feel otherwise :)
