### ISSUE TITLE
[BUG] Moosync crashes

### ISSUE THREAD

**Issue by AkiyamaMizuki3** [Moosync/Moosync#232]
**Describe the bug**
Sometimes (after around 2 hours of working) Moosync crashes and closes itself.

**Expected behavior**
Moosync should continue working without crashing.

- OS: Windows 10
- Version 21H2
- Moosync version: 8.1.1

**Additional context**
Crashes started happening after the last update (from 8.1.0 to 8.1.1), before it such behavior never happened. I think there is a possibility that this behavior specific for me and I don't know any guaranteed way to reproduce this bug. I would really appreciate it if you could solve the problem with so little information or give some advice on how to fix it without rolling back to an older version of the app.

**Comment by AkiyamaMizuki3** [comment]
![image](https://github.com/Moosync/Moosync/assets/67781417/6a21d6e6-2ae8-4d90-922b-914f05ecd1dc)
So, I have waited for crash again and checked logs. Maybe this can help somehow

**Comment by picafe** [comment]
try setting the scan interval in settings to -1

**Comment by Ovenoboyo** [comment]
Yup, the scan does seem to break something on Windows. I'm trying to rewrite the whole scanner so the process can be better and faster.

**Comment by Ovenoboyo** [comment]
Hi, sorry for the delay but this should be fixed in v9.0.0+. I'm closing this issue since it seems to be fixed, feel free to open it if you feel otherwise :)
