### ISSUE TITLE
Is there android support?

### ISSUE THREAD

**Issue by dillfrescott** [Moosync/Moosync#237]
Id love to use Moosync and was wondering if there was any sort of android support for on the go

**Comment by Ovenoboyo** [comment]
Android support is under work.. but lately I've not been able to find time to work on Moosync :''(

**Comment by dillfrescott** [comment]
Gotcha!

**Comment by Ovenoboyo** [comment]
Android development is being tracked in [this repo](https://github.com/Moosync/moosync_android). Closing this issue
