### ISSUE TITLE
[BUG] Buttons missing from compact view

### ISSUE THREAD

**Issue by Ovenoboyo** [Moosync/Moosync#24]
**Describe the bug**
Buttons like "play entire playlist", "Add all to library", "Add all to queue" are missing from compact view but are visible in classic view.

**Expected behavior**
Buttons should be consistent across views

![Screenshot_20211127_131428](https://user-images.githubusercontent.com/36789504/143672979-f5a669f2-ff52-4374-92e7-5c5a409de8ac.png)

**Buttons not visible ^**

![Screenshot_20211127_131415](https://user-images.githubusercontent.com/36789504/143672983-c13b236f-ab77-4d07-a0ce-9e432100d67e.png)

**Buttons visible ^**

**Comment by HaripriyaB** [comment]
I wish to work on this issue. Pls assign to me.
