### ISSUE TITLE
[BUG] Missing album artwork

### ISSUE THREAD

**Issue by Mason-17** [Moosync/Moosync#240]
**Describe the bug**
No album artwork for local files appears in the app.

**To Reproduce**

1. Add local files wherever
2. open app
3. refresh
4. no album art

**Expected behavior**
Be able to see album artwork.

**Screenshots**
![Screenshot 2023-06-06 114206](https://github.com/Moosync/Moosync/assets/122631948/004d9360-c4dd-4911-ae0c-fb4a54ee8c1b)

- OS: Both Windows and Arch

**Additional context**
Like two songs have their artwork.

**Comment by VZCE** [comment]
I have the exact same issue, only some of them appears.

**Comment by Mason-17** [comment]
> Is the album artwork embedded in the song or is it stored somewhere else as a file?

It is embedded in the song. They’re FLAC files.

**Comment by Mason-17** [comment]
Odd that it's happening for multiple file types> my

**Comment by Ovenoboyo** [comment]
That's odd, could you guys check the thumbnail folder if the thumbnails have been generated? You can find the folder location under settings > paths

**Comment by VZCE** [comment]
Only a few of them got generated

**Comment by Ovenoboyo** [comment]
I see, thanks for reporting. I'm underway reworking the file scanner. So it should be faster and should fix this issue as well.

**Comment by Ovenoboyo** [comment]
Hi, sorry for the delay but this should be fixed in v9.0.0+. I'm closing this issue since it seems to be fixed, feel free to open it if you feel otherwise :)

**Comment by Mason-17** [comment]
Hi. I actually forgot to check back in for the new version. My apologies. However, even though the album artwork seems to be generating in the cache (there are images in Appdata/Roaming/moosync/.thumbnails/), there is still no artwork appearing in the app.
