### ISSUE TITLE
[BUG] "Add To Playlist" List Doesn't Display All Playlists

### ISSUE THREAD

**Issue by The64thGamer** [Moosync/Moosync#248]
**Describe the bug**
The "Add to Playlist" option does not have a scrollable list for the playlists, which causes them to display off-screen when there are large amounts of playlists in the library (above 20, though depending on where the "Save to Playlist" button is on screen, this may cut off at the window even around 5 playlists)

**To Reproduce**

(Have a large number of playlists to start)
1. Go to queue
2. Right click on song
3. Click "Save to Playlist"
4. Attempt to save to a playlist low down in the options menu
5. See error

**Expected behavior**
The ability to scroll along the playlists provided and have all of them be able to be seen on-screen to click properly.

**Screenshots**
![](https://cdn.discordapp.com/attachments/677014118787710976/1120872786173378630/image.png)

- OS: Widnows
- Version v8.1.1

**Comment by Ovenoboyo** [comment]
It looks like the context menu library we are using is not updated any longer. Patching the existing implementation kinda seems like wasted effort to me. So I'd probably be switching to a new library or creating a custom context menu myself.

 I'm also migrating the whole app to Vue 3 so fixing this might take a bit longer than expected. Sorry
