### ISSUE TITLE
[FEATURE] Repeat queue functionality

### ISSUE THREAD

**Issue by Rigaln** [Moosync/Moosync#249]
Please understand that the text may not be the same because of the translation.

The repeat function repeats one song.
I would like to have a repeat function for all songs in the queue.

Thank you very much!

**Comment by Ovenoboyo** [comment]
Hey, thanks for suggesting this feature. I'll be sure to include it in the next release

**Comment by Ovenoboyo** [comment]
Re-reading this issue made me realize that the repeat queue is the default behavior of the app. If you have repeat turned off, after your last song, Moosync will start playing the first song in your queue again, essentially repeating the queue
