### ISSUE TITLE
[BUG] Login not working.

### ISSUE THREAD

**Issue by IIRONNIEII** [Moosync/Moosync#25]
(See reply)
I followed the instructions to create spotify api keys, but when I try to sign through my spotify, youtube or last.fm accounts, none work. I'm redirected to their respective sites to allow access to moonsync, yet after clicking allow I'm redirected to a site with the url, moosync.cf (ex:- https://moosync.cf/lastfm?token=CNz3dLV771xniU0NNDV8BjW3Y2zEOEm3), but it gives a 404 error and says, "There isn't a GitHub Pages site here." .

**To Reproduce**
1. Created the spotify app on the Spotify developer dashboard and enetered the keys.
2. Clicked connected to youtube, spotify and last.fm one-by-one
3. Redirected to respective to give permission and click allow access
4. See error "There isn't a GitHub Pages site here". 

[Screenshots: https://i.imgur.com/M3mGJD5.png, https://i.imgur.com/OGHYNs6.png, https://i.imgur.com/y4p0CQr.png]

 - OS: Windows 7
 - Version: v0.0.8

![spotify](https://user-images.githubusercontent.com/60402476/143830753-f0c0bda5-d619-407d-b1c1-2149ad4c5f7e.png)
![youtube_music](https://user-images.githubusercontent.com/60402476/143830761-e1ece66e-fec2-42b8-a69f-05ae3403ef3e.png)
![lastfm](https://user-images.githubusercontent.com/60402476/143830764-60aaba2a-3112-463d-8ca1-a4c83dd78515.png)

**Comment by IIRONNIEII** [comment]
[Update]
Hello,

I recently checked the app's about page which includes the url, "https://moosync.app/" instead of, "https://moosync.cf/". On being redirected I changed the cf to app and it works fine you can look into that...

Additionally I'm really enjoying the app, it's looks good and it has the services I use. Plus, even though youtube and spotify are working, the last.fm signup still doesn't work. Should I publish another issue?

Anyways keep up the good work.

**Comment by Ovenoboyo** [comment]
> [Update] Hello,
> 
> I recently checked the app's about page which includes the url, "https://moosync.app/" instead of, "https://moosync.cf/". On being redirected I changed the cf to app and it works fine you can look into that...
> 
> Additionally I'm really enjoying the app, it's looks good and it has the services I use. Plus, even though youtube and spotify are working, the last.fm signup still doesn't work. Should I publish another issue?
> 
> Anyways keep up the good work.

Thank you for pointing this out. I didn't realize this when we moved domains. It should be fixed in https://github.com/Moosync/Moosync/commit/c9c6a5f05ce6b00b9010b2a6db84c6b465c00aad

Since this is a functionality breaking bug, ill post a new release by tomorrow.
