### ISSUE TITLE
Close to tray not working [BUG]

### ISSUE THREAD

**Issue by Zineffable1** [Moosync/Moosync#252]
Windows 10 Pro

Tried having the box checked and unchecked.

**Comment by Ovenoboyo** [comment]
If you have the box checked and you close the app, does it close straight away?

**Comment by Zineffable1** [comment]
Yep

**Comment by shoraaa** [comment]
This can be temporary fixed by close the tray in the task bar instead of use the close button. Still a bug though.

**Comment by Zineffable1** [comment]
Cool, cheers.
