### ISSUE TITLE
[BUG] playerctl play-pause will play but not pause

### ISSUE THREAD

**Issue by CipherJay** [Moosync/Moosync#256]
Playerctl can play, but not pause the player using the play-pause command.

- Install as flatpak
- Use playerctl to play/pause the music

Expected behavior:
I expect it to be able to pause and resume with my key bind I have set up to trigger the play/pause toggle using playerctl play-pause. If paused or not yet started, it will play. Once playing, it will not pause.

- OS: NixOS
- Version 23.5

I love this app you've made. I will make due with manually pausing for now, continue to promote Moosync, and hope this isn't a difficult fix. If there is some other information you need or any way I can help, please let me know.

**Comment by Ovenoboyo** [comment]
Turns out the app will not receive the play-pause event if ```canPlay``` functionality is set to false. This should be fixed in an upcoming release. If this is a deal-breaker for you, you could also get the development build from the ```actions``` tab in Github (There is no development build for flatpak or snap, you'll have to use .tar.gz or the AppImage)

**Comment by Ovenoboyo** [comment]
Oh I think you misunderstood me. I had already pushed a fix for this, I was just informing you about it. Its just that right now the fix isn't published in a release, instead its available as a development build.

If you scroll down [on this page](https://github.com/Moosync/Moosync/actions/runs/5620131292) you can find download links for your platform (I believe the easiest one to use is the AppImage)

It would be great if you could try out the above build and let me know if everything is working as expected. 

Thanks.
