### ISSUE TITLE
[BUG] App crashes when encountering weird characters in m3u playlists

### ISSUE THREAD

**Issue by NotGabe001** [Moosync/Moosync#260]
**Bug description**

I have an m3u playlist that contains "ω" (lowercase omega) and Moosync doesn't seem to like that.
Running the flatpak from the command line using `flatpak run app.moosync.moosync`, it says:

```thread '<unnamed>' panicked at 'byte index 1 is not a char boundary; it is inside 'ω' (bytes 0..2) of `ω-3 - Deluge Dirge`', /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/str/mod.rs:678:13```

**To Reproduce**

Create an m3u playlist that contains a weird character such as "ω" in the your music directory, then open Moosync.
It will then crash with the error above near the end of the output. If the playlist containing the character is deleted, the app will start normally without any problems.

- OS: Fedora 38
- Version 9.0.0

**Comment by Ovenoboyo** [comment]
Rip why didn't I think of this before

**Comment by NotGabe001** [comment]
I just now discovered that it only crashes on first startup. Works fine otherwise.

Here's a simplified version of the playlist file. It still crashes the app.

```
#EXTM3U
#EXTINF:178488,ω-3 - Deluge Dirge
~/Music/Splatune_3/Salmon_Run/Deluge_Dirge.mp3
```

It was created from the Retro Music Player app on my phone, and then I copied it to my PC and changed the directories so it would work. It crashes whether the music it's pointing to exists or not. It works fine in Rhythmbox though.

**Comment by Ovenoboyo** [comment]
Should be fixed in the next release. Unfortunately I don't have development builds for flatpak :''(. 

If you want, you can check out other available builds [here](https://github.com/Moosync/Moosync/actions/workflows/build.yml)
