### ISSUE TITLE
[BUG] v10.0.0 right-click context menu doesn't work in settings

### ISSUE THREAD

**Issue by ApplePie420** [Moosync/Moosync#269]
**Describe the bug**
In version 9.0.2 (and earlier), you can click with right mouse button for example on a theme, and a context menu with some additional options (such as edit, remove, copy code etc.) shows up. That doesn't work in v10.0.0. Tested on Windows 10 and Manjaro 22 Talos with Xfce DE. 
Color picker while creating new theme also doesn't work under this version.

**To Reproduce**
Download latest release of Moosync, try to import a new theme, and then edit it, or create a new theme.

**Expected behavior**
Context menu shows up, as it does in version 9x and earlier. Color picker should also show up.

**Screenshots**
Don't think that's possible

- OS: Windows 10 build 19045.3324
- OS: Linux Manjaro 22 Talos, Xfce 
- Version v10.0.0

**Additional context**
None

**Comment by Ovenoboyo** [comment]
[This build](https://github.com/Moosync/Moosync/actions/runs/5957641330) should fix the edit themes functionality. The color picker right now is unstyled but I'm hoping I would be able to style it by the next release

**Comment by Ovenoboyo** [comment]
Moving to vue3 was a major change and broke some existing components. Sorry for the inconvenience
