### ISSUE TITLE
[BUG] Youtube playlists not showing.

### ISSUE THREAD

**Issue by PowerRangerX** [Moosync/Moosync#274]
**Describe the bug**
Searching for youtube playlists brings no results, or the results are incorrect and the playlists have no songs in them. Also searching for any playlist by URL doesn't work, like at all. Tried searching for both public and private/unlisted playlists.

**To Reproduce**

1. Go to the search bar.
2. Set the search filters to Youtube, and playlists or not, search on any filter songs, artists etc.
3. Search for any playlist by name or by URL.
4. Wait for results.
5. Nothing helpfull shows up.

**Expected behavior**
Correct playlist should appear when searched for.

**Screenshots**
![Screenshot 2023-09-11 154028](https://github.com/Moosync/Moosync/assets/85272502/32bda1cb-62d8-48c5-82c2-cfaa8f956005)

- OS: Windows
- Version 22H2
- Build 22621.2215

**Additional context**
I am doing this while not logged into any services, don't know if that should affect anything though.

**Comment by PowerRangerX** [comment]
I know you can add playlists via URL on the Playlists section and it works like a charm but I think the search function should also show playlists atleast when searching with them URLs.

**Comment by Ovenoboyo** [comment]
Turns out Youtube has started appending VL to their playlist IDs (Not sure if its youtube or just the library we are using). Which was breaking the playlist content functionality. I'll do a hotfix release in a few hours. It should fix the issue
