### ISSUE TITLE
[BUG] System settings checkboxes display not working

### ISSUE THREAD

**Issue by jon-vfb** [Moosync/Moosync#277]
The current display of most of the checkboxes of the app looks like this:

![image](https://github.com/Moosync/Moosync/assets/111185427/147e6e6b-06b9-4d60-b5af-85bff6349e56)

I have been able to reproduce this error in both: Windows 11, and a Windows 11 virtual machine. No matter what I do the checkboxes do not display the current state correctly, but the functionality seems to work alright.

**Comment by donCESAR12345** [comment]
Can reproduce in Fedora 38

**Comment by Crunchbits** [comment]
Can reproduce in Windows 10.

**Comment by dan-ky** [comment]
As I commented on the other bug report about the "heart not displaying/working", I have the same problem in the system settings: I can not see what boxes are checked and which ones are not (manjaro, flatpak)

**Comment by Ovenoboyo** [comment]
Yup, saw that and realized I forgot to do a release 2 weeks ago xD

Pushing a build for flatpak now

**Comment by jon-vfb** [comment]
thanks! also @Ovenoboyo, and the rest of the Moonsync team, the app is great! I am looking forward to future updates!
