### ISSUE TITLE
add CONTRIBUTING.md

### ISSUE THREAD

**Issue by khareyash05** [Moosync/Moosync#28]
I would like to create a file contributing.md and add following -
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on this as a part of SWOC 21

**Comment by Ovenoboyo** [comment]
Sure, go ahead. ill assign this issue to you

**Comment by khareyash05** [comment]
@Ovenoboyo Created a PR Have a look
