### ISSUE TITLE
[BUG] Heart button does nothing on Flatpak version.

### ISSUE THREAD

**Issue by psi4j** [Moosync/Moosync#280]
The heart button seems to do nothing on my player. Running Arch Linux with the flatpak version. I realize this was a past issue that was fixed, so I'm not sure if there's something I'm missing or doing wrong. It used to work on my NixOS build, also running flatpak, so I'm confused about why it would not work on Arch (same desktop, also running NVIDIA). I've also tried changing my custom theme around to see if it's just not showing it correctly due to the coloring hiding the effect, but nothing seems to change the heart. I'm using the default theme building options in the player. I can also confirm I am experiencing the same issue using the standard AUR package. Here is the error it throws when I press the button:

```
[10-06-2023 11:39:48] [ERROR] [Renderer]:  [Error: An object could not be cloned.]
```

My system is running latest everything Arch Linux, running Hyprland, on Wayland with XWayland support, and nvidia-dkms. I suspect this may be an issue that is outside of Moosync, but I don't have enough knowledge of the inner workings of the application to know what it could be.

A side question while we're here: I wanted to ask what the recommended install method is for Arch Linux (+Nix) for the most clean experience.
Three choices I am considering are:
AUR
Flatpak
Nix Flake

Please let me know if there are any details I may have missed and would help in figuring out what's causing this issue. Thank you for your time and all your hard work on this next level music player. It truly is the best thing out there, if more people only knew.

**Comment by dan-ky** [comment]
Have the same problem on Manjaro with flatpak version 

PS: @CipherJay can you maybe change the title, so one can see what this issue is about, without having to open it?

**Comment by Ovenoboyo** [comment]
Ah thanks for reporting this. I'll try to get a fix out this weekend

**Comment by Ovenoboyo** [comment]
As for the install method, I'd always recommend using your system's package manager (aur in this case) since I don't really get a lot of time to check everything on flatpaks

**Comment by psi4j** [comment]
Resolved with an update.
