### ISSUE TITLE
Unable to fetch more than 100 songs per Youtube playlist[BUG]

### ISSUE THREAD

**Issue by Zy-XD** [Moosync/Moosync#287]
**Describe the bug**
The program refuses to fetch more than 100 songs per Youtube playlist, when using the fetch button, it will load forever

**To Reproduce**

1. Import new Youtube playlist
2. Receive only 100 songs if it contains more than 100

**Expected behavior**
Import all songs contained within playlist

- OS: Windows 10
- Version v10.1.2

**Comment by Ovenoboyo** [comment]
Once you import a playlist, you can scroll to the bottom of the current song list to fetch the next batch of 100 songs. This is don't to avoid making unnecessary requests to Youtube.

You could also press the "fetch all" button right below the playlist's name to get all the songs in a playlist. The button looks like a curved arrow
