### ISSUE TITLE
Automatic Update within program[FEATURE]

### ISSUE THREAD

**Issue by Zy-XD** [Moosync/Moosync#288]
**Is your feature request related to a problem? Please describe.**
Ease of use when a new update comes, not having to open the browser to find and download and install the new update

**Describe the solution you'd like**
An automatic update feature to update client when new update rolls out

**Describe alternatives you've considered**
Update check button within client

**Comment by Ovenoboyo** [comment]
There is an auto-updater already present in the app. It only works on windows and AppImages in linux since the recommended way to install / update Moosync in other cases is through the system's package manager. 

What platform are you on?
