### ISSUE TITLE
[BUG] Some metadata not published

### ISSUE THREAD

**Issue by cathartyc** [Moosync/Moosync#292]
Hi, first of all thanks for the amazing job here, I am using Moosync every day and it's great!

**Describe the bug**
Using `playerctl` I noticed that Moosync does not publish information about the track length, the current position and the track id (not sure what it is).
This is independent on the reproduced track. This does not let me use `playerctl position +5` to go further in the track, nor let me display the current positiion on waybar.

**Screenshot**
![image](https://github.com/Moosync/Moosync/assets/67878876/737ff7f9-73ff-48f5-a81d-edddd26c7f7d)

**Additional context**
I am on Fedora 38, using the `copr` version.

**Comment by cathartyc** [comment]
I am not sure if this is a bug or a missing element: if needed, I can try to inspect the code and work on it in a month or two :+1:

**Comment by Ovenoboyo** [comment]
You're right, it would require https://github.com/Moosync/MediaController to be patched to accept the missing elements.

Shouldn't take me too long
