### ISSUE TITLE
[BUG] App quits after a while even while playing music

### ISSUE THREAD

**Issue by siddharthkumarjha** [Moosync/Moosync#294]
**Describe the bug**
As the description says I have downloaded `moosync-bin` from AUR and the app is working great except for a small problem, the app quits after a while even when its playing some music. I would have understood this behavior if moosync was idle and hence to save resources decided to quit itself but why do this while playing a song?

I have been looking around in settings and wiki but I can't find anyway to turn off this behavior either.

**To Reproduce**

1. launch moosync
2. start any playlist
3. play for 2-3 hours approx. (edit: Just timed it, started the player at 3:08 and around 4:05 it quit itself. so approx 1 hr.)
4. The app quits after the time period even if music is playing

**Expected behavior**
When the app is in use the app should keep working but if it's idle it should quit after a while. or, provide a way to turn this feature off.

- OS: Garuda Linux, (arch linux + themed KDE)
- Version 10.2.0-1

**Comment by Ovenoboyo** [comment]
It's most likely a bug, the app has no feature to shut down by itself to save resources.

Could you try checking the logs (perhaps posting them here) at the time of crash? They are found at ```~/.config/moosync/logs```

**Comment by siddharthkumarjha** [comment]
> It's most likely a bug, the app has no feature to shut down by itself to save resources.
> 
> Could you try checking the logs (perhaps posting them here) at the time of crash? They are found at `~/.config/moosync/logs`

Here are the logs, I have uploaded them to a pastebin,

https://bin.garudalinux.org/?584b0d6d656084ca#8QKngAsMLfoztB55UVG2AMfSdWv38TKCrnRbvEBbpARH

I have tested this several times and have noticed that the player quits dot at 1hr time frame and the only thing that stands out to me is this block,

~~~
[10-31-2023 08:54:21] [INFO] [Main]:  Checking for beta autoupdate feature for deb/rpm distributions
[10-31-2023 08:54:21] [INFO] [Main]:  Found package-type: deb
[10-31-2023 08:54:22] [INFO] [Main]:  Setting scan task for 60 minutes
[10-31-2023 08:54:22] [INFO] [Main]:  Setting update check task for 3 hours
[10-31-2023 08:54:22] [INFO] [Main]:  Setting scrape task for 30 minutes
[10-31-2023 08:54:23] [INFO] [Main]:  Checking for update
[10-31-2023 08:54:27] [INFO] [Main]:  Update for version 10.2.0 is not available (latest version: 10.2.0, downgrade is disallowed).
~~~
I believe that scan task is perhaps the reason for this issue.

**Comment by Ovenoboyo** [comment]
That's very possible. Does the app also crash when you go-to

Settings > paths and click the refresh icon?

**Comment by siddharthkumarjha** [comment]
> That's very possible. Does the app also crash when you go-to
> 
> Settings > paths and click the refresh icon?

Yes, I just checked and clicking on the icon after approx 20-30 seconds the app crashed.

**Comment by siddharthkumarjha** [comment]
I just found about libvips from wiki (stupid me, should have tried that first) and tested moosync, all problems are gone and the app is running great.

On a side note please consider adding `libvips` to the dependency list of moosync on AUR, `libvips` is available in official arch repos.

**Comment by Ovenoboyo** [comment]
I'll do that, thanks for figuring it out
