### ISSUE TITLE
Youtube&Spotify Playlists have Spotify songs being pulled from YT videos [BUG]

### ISSUE THREAD

**Issue by RinnosukeKuto** [Moosync/Moosync#347]
**Describe the bug**
Let me preface this by saying I do NOT have Spotify premium, so if that is the cause, this is not a bug; however, in the off-chance that isn't the cause...
At times, when I'm making a playlist of queueing together YouTube and Spotify tracks, the app will make it so, when a Spotify song comes up, it'll look for a video of the same name on YouTube and play that, rather than the track on Spotify... So, if one song only has a preview on YouTube, it'll stop abruptly a few seconds in; or, at times, you may end up with a videogame playthrough playing for a hour and half over a 3 minutes song.

**To Reproduce**
Steps to reproduce the behavior: In my case, it's simple: the songs "ID" from ZYTOKINE, on Spotify, where the song will stop 10~ seconds in because that's the length of the song preview on YouTube, and the song "Final Boss Battle #2" from 3R2, Triodust, and CreSpirit (from the Rabi-Ribi OST, volume II/2) ends up playing from a playthrough video despite it being a Spotify song that should last 11:28 minutes, so you hear someone playing the game. This happens in a queue of YouTube and Spotify songs together, but at this point (not sure if a clean install and login would change it) it still happens even when I queue the Spotify playlist alone.

**Expected behavior**
The expected behavior is that it should pull from Spotify itself for Spotify playlist songs and from YouTube for YouTube videos.

**Screenshots**
![image](https://github.com/Moosync/Moosync/assets/162490526/f8e2c548-94ff-43d6-a38b-969a023df8c6)
(Of course it can't show much, but this is to show the song is technically from Spotify with the Spotify logo)

- OS: Windows 10
- Version 22H2

**Additional context**
The very first thing I did once setting the software up was to shuffle the playlists together, rather than try and play them separately, so I can't be sure if on a "clean install" that would happen all the same.

**Comment by Ovenoboyo** [comment]
This unfortunately is how it is intended to be with Spotify free. If you do have a Spotify premium, you could put your credentials under librespot in settings and it should fetch the songs directly from Spotify for you.

If you would like to change the track being played from YouTube, you could right click on the track in the queue and select "incorrect playback". This should allow you to manually select the correct song from youtube

**Comment by RinnosukeKuto** [comment]
Alright, if it's intended, then that's that! Thank you very much!
