### ISSUE TITLE
[BUG]Spotify not connecting.

### ISSUE THREAD

**Issue by IllNoobis** [Moosync/Moosync#357]
**Describe the bug**
Cannot connect to spotify. I reach the website click open in moosync, it redirects, nothing happens.

**Expected behavior**
Connection to spotify.

**Screenshots**
![image](https://github.com/user-attachments/assets/3d2f5145-f5a5-4ce2-922a-17cfd686d423)
![image](https://github.com/user-attachments/assets/d5ad7179-e5f8-4454-9f4a-e4c280a27275)

- OS: [Win 11 Home]
- Version [23H2}

**Additional context**
Tried using code, didnt work.

**Comment by IllNoobis** [comment]
Tried last fm. it worked. connected spotify to last fm _**NOT MOOSYNC**_
it worked.

**Comment by Ovenoboyo** [comment]
Can you try to see if there is anything relevant under settings > logs after you enter the code?

**Comment by IllNoobis** [comment]
[moosync-19-08-2024.log](https://github.com/user-attachments/files/16669684/moosync-19-08-2024.log)
Here I found the log files.

#116

**Comment by Ovenoboyo** [comment]
Could you maybe post a screenshot of how you configured the app in Spotify developer portal? Be sure to hide your client I'd and secret though

**Comment by IllNoobis** [comment]
> Could you maybe post a screenshot of how you configured the app in Spotify developer portal? Be sure to hide your client I'd and secret though


![image](https://github.com/user-attachments/assets/304c9f6c-7512-484a-979a-7a038dfbda64)
![image](https://github.com/user-attachments/assets/a17dd099-b5b5-4332-b532-ad30fa62069a)
![image](https://github.com/user-attachments/assets/a74094b1-74e3-473d-93fe-e72447c0577c)
![image](https://github.com/user-attachments/assets/712063d9-10cd-4929-a50a-33dee1b544e9)
![image](https://github.com/user-attachments/assets/ddefffb2-895e-44f7-8797-467671dfd239)

**Comment by IllNoobis** [comment]
I tried it again, copied the secret key and it worked.
