### ISSUE TITLE
[BUG] Librespot Bad Credentials when credentials are correct.

### ISSUE THREAD

**Issue by qilinmoe** [Moosync/Moosync#363]
**Describe the bug**
Librespot fails to log in using spotify credentials with a Bad Credentials error even when they're correct.

**To Reproduce**

1. Open Moosync
2. Set Spotify username and password on settings

**Expected behavior**
Log in successfully and be able to play songs

**Screenshots**
![image](https://github.com/user-attachments/assets/332a3719-5826-4921-a2f9-20561cf90121)

- OS: [Windows 10 Pro 22H2]
- Version [v10.3.2]

**Additional context**
Enabling debug logging and doing the process again doesn't show anything else relevant that didn't already show up.

If there are saved text logs that I can provide, let me know where they're located and I will. I believe they'd be better than a screenshot from the log screen.

**Comment by qilinmoe** [comment]
After a bit more research, it seems to be an issue with librespot (https://github.com/librespot-org/librespot/issues/1308)
Hoping this can be fixed soon!

As a relatedly unrelated feedback, it would be awesome to get some info where we put credentials in if it successfully logged in or not.

**Comment by Ovenoboyo** [comment]
Yup you're right. Spotify recently disabled their username/password login. A good this though is that we already implemented Spotify OAuth in the new tauri version of Moosync (https://github.com/Moosync/tauri/commit/bd24d7fc4d764a1a5f7ca424c1bbc670c2bd5910). I hope to get a release out for it soon

**Comment by qilinmoe** [comment]
That's awesome! Hoping for a release soon too! ^^

Thank you for the hard work and the amazing app!
