### ISSUE TITLE
[FEATURE] Media key support (only pause and play works)

### ISSUE THREAD

**Issue by LooLooAsuna** [Moosync/Moosync#72]
Pause and play media keys works but i cant seem to get prev and next functioning
not sure if this is on my end or just not currently a feature

**Comment by M-erb** [comment]
What an amazing music player/ manager. I tried it today using the flatpak version on Pop!_OS and it really is amazing. Thank you for everyone who is helping create this. One thing I noticed is that the media key support did not work at all. Which led me here and found this issue. I thought I would add to this one. Is there a flatpak permission I need to set to allow it work?

**Comment by Ovenoboyo** [comment]
Media key support is going to be broken for the time being for flatpak. https://github.com/flathub/app.moosync.moosync/issues/1
