### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by Terkyz** [Moosync/Moosync#83]
**Is your feature request related to a problem? Please describe.**
Is not a problem. It just seems to me that Moosync can reach a larger audience thanks to this. Also, I personally find it more comfortable to update directly from Flatpak than to reinstall Moosync every time there is an update.

**Describe the solution you'd like**
A Flatpak version of Moosync.

**Describe alternatives you've considered**
That in the future, a Flatpak version of Moosync will be made.

**Additional context**
Nothing special, forgive me Moosync devs for my barrage of requests and bug reports, specifically this is not something strictly necessary, it just seems to me like a good option in the future!

**Comment by Ovenoboyo** [comment]
I tried building for flatpak. For now the extensions don't work and the app won't close xD. The only way to stop the app is to kill it using ```flatpak kill```. And i don't really have any experience with flatpak either so debugging it is really difficult for me.

I'll keep trying to get it working but... don't keep high expectations

**Comment by Ovenoboyo** [comment]
Ok plot twist... I somehow managed to get it working

**Comment by Ovenoboyo** [comment]
Moosync is now available on flathub. I'll update the readme soon
