### ISSUE TITLE
[BUG] rpm has missing dependency

### ISSUE THREAD

**Issue by skamansam** [Moosync/Moosync#89]
**Describe the bug**
When I start moosync after installing the rpm on Fedora 36, I get the following error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/opt/Moosync/resources/app.asar/node_modules/sharp/lib/sharp.js:31:9)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Moosync/resources/app.asar/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
```

After running `dnf install vips-*`, it works.  

**To Reproduce**

1. run `sudo dnf remove vips-*` (to make sure the vips packages aren't already installed)
2. install moosync with `sudo dnf install /path/to/moosync*.rpm`
3. run `moosync`'

**Expected behavior**
The application to run and the moosync window to open.

- OS: Fedora Linux 36
- Version 2.1.0

**Additional context**
Downloaded rpm from the moosync website.

**Comment by Ovenoboyo** [comment]
Yup, Moosync requires libvips to work. I don't really have any experience with dnf or fedora so i'm not sure how i could add vips as a dependency. 

Right now the best I can do is add this in a "known bugs" section in the wiki.

Buf if you know how this could be handled better, feel free to send a PR. Here's the [moosync.spec](/Moosync/Moosync/tree/main/rpm/moosync.spec) file I use to build on [COPR](https://copr.fedorainfracloud.org/coprs/ovenoboyo/Moosync/) if you want to have a look.

**Comment by LespiletteMaxime** [comment]
Hello,
Same issue for .deb package

**Comment by Ovenoboyo** [comment]
> Hello, Same issue for .deb package

I have added the dependency for deb package [here](https://github.com/Moosync/Moosync/blob/609a0ee820d2b591d7720817b9b8b16567811a5c/vue.config.js#L107). Hope its fixed by the next release

**Comment by Ovenoboyo** [comment]
> Hello,
> Same issue for .deb package

As a temporary fix you can do ```sudo apt-get install libvips-dev```
