### ISSUE TITLE
[BUG] Spotify Logs out on close of app

### ISSUE THREAD

**Issue by UnixPhonez** [Moosync/Moosync#93]
**Describe the bug**
Spotify logs out of closing of the app
**To Reproduce**

1. Go to moosync
2. quit moosync

**Expected behavior**
for spotify to stay logged in 

- OS: fedora linux 36
- Version [e.g. v3.0.0]

**Comment by Ovenoboyo** [comment]
Starting from v4.0.0, refresh tokens should be stored irrespective of them being encrypted or not. This should probably fix your issue. Feel free to open a new issue or comment on this one if this problem persists :)
