### ISSUE TITLE
[BUG] App crashes on launch (Error while fetching theme)

### ISSUE THREAD

**Issue by mikaelkundert** [Moosync/Moosync#94]
**Describe the bug**
When I install Moosync over snap (or Ubuntu's Software GUI) and launch it, it closes/crashes right away.

**To Reproduce**

When launching from GUI, I get this dialog:
![image](https://user-images.githubusercontent.com/93661/170960194-1b5f7dab-6b4f-4df5-b2cb-6de2b6fc0398.png)

When launching from CLI, it reports following warning and error:
```
$ moosync 

DevTools listening on ws://127.0.0.1:44805/devtools/browser/89d4beb4-b387-4c1d-8021-98942c8af584
[05-30-2022 12:15:38] [ERROR] [Main]:  Error while fetching theme
[05-30-2022 12:15:39] [WARN] [Main]:  APPIMAGE env is not defined, current application is not an AppImage
/opt/Moosync/moosync --enable-crashpad: symbol lookup error: /opt/Moosync/resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-linux-x64.node: undefined symbol: vips_fail_on_get_type
```

**Expected behavior**
I expect the app to be opened and being able to use and interact with it.

- OS: Linux, Ubuntu
- Version: Ubuntu 20.04 LTS

**Comment by Ovenoboyo** [comment]
Turns out the ```symbol lookup error``` is usually caused when you have multiple libvips libraries installed. IIRC ubuntu provides 2 libvips libraries ```libvips42``` and ```libvips-dev```. The immediate solution would be to remove one of them preferably ```libvips42```

Could you try doing ```sudo apt remove libvips42``` and see if it works?

**Comment by mikaelkundert** [comment]
`libvips42` seemed to be shipped when installing `libvips-dev`:
```
$ sudo apt install libvips-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  gir1.2-vips-8.0 libvips-tools libvips42 nip2
The following NEW packages will be installed:
  gir1.2-vips-8.0 libvips-dev libvips-tools libvips42 nip2
0 upgraded, 5 newly installed, 0 to remove and 4 not upgraded.
Need to get 7 004 kB of archives.
After this operation, 27,3 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

If I remove `libvips42` after command above, I get following error:
```
$ moosync 

(moosync:69889): Gtk-WARNING **: 16:18:54.638: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(moosync:69889): Gtk-WARNING **: 16:18:54.644: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(moosync:69889): Gtk-WARNING **: 16:18:54.646: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name

DevTools listening on ws://127.0.0.1:45327/devtools/browser/449d1bfc-c40a-445d-9294-d69a96c7bb59
[06-02-2022 16:18:54] [ERROR] [Main]:  Cant access /usr/share/themes
[06-02-2022 16:18:54] [ERROR] [Main]:  Error while fetching theme
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
[06-02-2022 16:18:55] [INFO] [Main]:  SNAP env is defined, updater is disabled
/snap/moosync/2/app/moosync --no-sandbox --enable-crashpad: symbol lookup error: /snap/moosync/2/app/resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-linux-x64.node: undefined symbol: vips_fail_on_get_type
[70109:0602/161855.861792:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -3
```

When re-installing `apt install libvips-dev` again, I don't get SSL handshake error, and the GUI pops up for subsecond until it crasehs having following CLI output:
```
$ moosync 

(moosync:70620): Gtk-WARNING **: 16:20:31.218: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(moosync:70620): Gtk-WARNING **: 16:20:31.224: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(moosync:70620): Gtk-WARNING **: 16:20:31.226: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name

DevTools listening on ws://127.0.0.1:45605/devtools/browser/1630c753-f85a-4b79-9661-c468a7403323
[06-02-2022 16:20:31] [ERROR] [Main]:  Cant access /usr/share/themes
[06-02-2022 16:20:31] [ERROR] [Main]:  Error while fetching theme
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
[06-02-2022 16:20:31] [INFO] [Main]:  SNAP env is defined, updater is disabled
/snap/moosync/2/app/moosync --no-sandbox --enable-crashpad: symbol lookup error: /snap/moosync/2/app/resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-linux-x64.node: undefined symbol: vips_fail_on_get_type
```

**Comment by mikaelkundert** [comment]
With App image (3.0.1), I moved it to `/usr/local/bin/moosync` then:

```
$ moosync 

DevTools listening on ws://127.0.0.1:37583/devtools/browser/fe90c012-6927-4c44-b3b5-64dc2d9141a2
[06-03-2022 13:15:36] [ERROR] [Main]:  null
[06-03-2022 13:15:36] [ERROR] [Main]:  Error while fetching theme
[06-03-2022 13:15:37] [INFO] [Main]:  Checking for update
[06-03-2022 13:15:37] [INFO] [Main]:  Generated new staging user ID: 3079c2b8-00fa-56aa-a3bd-44a3672a4528
multiple times> Trying to find local cover for ....
[06-03-2022 13:15:39] [INFO] [Main]:  Update for version 3.0.1 is not available (latest version: 3.0.1, downgrade is disallowed).
multiple times> Trying to find local cover for ....
/tmp/.mount_moosynTm97lp/moosync --enable-crashpad: symbol lookup error: /tmp/.mount_moosynTm97lp/resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-linux-x64.node: undefined symbol: vips_fail_on_get_type
```

Then:
```
$ sudo apt install libvips-dev
sudo apt install libvips-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libvips-dev is already the newest version (8.9.1-2).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```

And then:
```
$ moosync 

DevTools listening on ws://127.0.0.1:45717/devtools/browser/4ea9f194-29b7-4db1-9a3d-0eda1c7ba438
[06-03-2022 13:16:03] [ERROR] [Main]:  Error while fetching theme
[06-03-2022 13:16:04] [INFO] [Main]:  Checking for update
/tmp/.mount_moosynalw0qN/moosync --enable-crashpad: symbol lookup error: /tmp/.mount_moosynalw0qN/resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-linux-x64.node: undefined symbol: vips_fail_on_get_type
```

Thanks for debugging with me :+1:

**Comment by mikaelkundert** [comment]
With DEB:

```
$ sudo dpkg -i ~/Downloads/Moosync-3.0.1-linux-amd64.deb 
Selecting previously unselected package moosync.
(Reading database ... 288811 files and directories currently installed.)
Preparing to unpack .../Moosync-3.0.1-linux-amd64.deb ...
Unpacking moosync (3.0.1) ...
dpkg: dependency problems prevent configuration of moosync:
 moosync depends on default; however:
  Package default is not installed.

dpkg: error processing package moosync (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 moosync
```

**Comment by Ovenoboyo** [comment]
oof this is more weird than I thought. What happens if you completely remove libvips-dev and libvips42?

**Comment by Ovenoboyo** [comment]
I might have figured out why this is happening. It seems Ubuntu 20.04 (focal) ships libvips-dev 8.9.1 while the current version of sharp requires atleast 8.12.1

So I think downgrading sharp seems to be the only solution to ensure compatibility.

**Comment by Ovenoboyo** [comment]
Turns out downgrading sharp is causing a lot of issues with other libraries. Lower versions of sharp depend on an older version of libffi. With flatpak there is this weird issue of libicui18n.so.70 (Which I couldn't find the cause nor the fix for it). Imo it's getting really difficult to handle all these dependencies just to make it work in Ubuntu <22.04.

So the fix right now would be removing libvips-dev dependency from the deb and snap and making things done by sharp **optional** (probably toggleable in settings). And if you want sharp to work, I'll put up a guide on how to manually compile the proper version of libvips. 

Hope this is acceptable.

**Comment by mikaelkundert** [comment]
> So the fix right now would be removing libvips-dev dependency from the deb and snap and making things done by sharp optional (probably toggleable in settings). And if you want sharp to work, I'll put up a guide on how to manually compile the proper version of libvips.

I don't know if this was targeted for development, or for me. However, I don't know how I manipulate/fork dependencies in deb or snap, nor how to do things in optionally in sharp, since I have not looked into the source code at all.

I guess I have a reason to upgrade to 22.04 LTS :package:

**Comment by Ovenoboyo** [comment]
I'm sorry for writing it confusingly. The fix I posted above was meant for development. I'll implement it. You don't have to worry about anything.

How it would affect you is if you're below Ubuntu 22.04, you'll have certain features missing. If you want them to work, you'll have to compile libvips from source.

Dont worry, I plan to keep it really simple. Compiling libvips from source would be a matter of running 2-3 commands ( and understanding them)

**Comment by mikaelkundert** [comment]
Tried out 4.0.0 release (dev package), and I'm still getting this.

**Comment by Ovenoboyo** [comment]
Ok that's weird. Can you remove libvips and libvips-dev using **apt** and then following the **Building libvips from source** part from here https://github.com/libvips/libvips/wiki/Build-for-Ubuntu.

Do let me know if you get stuck somewhere.
