### ISSUE TITLE
Add YouTube features like browse channels.

### ISSUE THREAD

**Issue by Ace-c** [Moosync/Moosync#95]
Add an option to browse channels like when you play any song I just wanted to open that song channel.

**Comment by Ovenoboyo** [comment]
Currently this feature exists only for Spotify and is restricted to only Spotify artists. I'll try to implement it for Youtube too.

**Comment by Ace-c** [comment]
Thnku

**Comment by Ovenoboyo** [comment]
From v4.0.0 you can fetch songs of an artist explicitly (See screenshot below). Hope this fulfills your request.

![image](https://user-images.githubusercontent.com/36789504/176284662-550c21af-5cd7-43a1-ab24-29e9e46ff151.png)
