### ISSUE TITLE
[BUG] Failed to install in Arch Linux

### ISSUE THREAD

**Issue by argonarch** [Moosync/Moosync#97]
In the installation process occurs:

Error /home/user/.cache/yay/moosync/src/Moosync-3.0.1/node_modules/sharp: Command failed.
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

Solution:

add to required packages: [node-gyp](https://archlinux.org/packages/community/any/node-gyp/)

**Comment by Ovenoboyo** [comment]
node-gyp should be installed as a part of ```build`` process of the AUR package. But nevertheless i could add it as as make dependency
