### ISSUE TITLE
getting multiple applets on minizing to trey

### ISSUE THREAD

**Issue by Klavrin** [Moosync/Moosync#98]
When minimizing the app to trey I get multiple applets

1. Launch the app
2. Be sure that "Minimize to trey on close" feature is on [ Settings - System - System Settings ]
3. Close the app
4. See the applet appearing
5. Repeat

Expected behavior: Every time I close the app I am left with only one applet, instead of getting +1 every time I close the app. 

![moosync1](https://user-images.githubusercontent.com/59708142/173051289-4d468a28-93f0-4ff9-84d6-70d193f90bd8.png)

- OS: Linux Mint
- Version: 20.3 (Una)

**Comment by Ovenoboyo** [comment]
How did you install the app (E.g from Flatpak, Snap, AUR, etc). And is there any error / warning in ```Settings > Logs```  when this behaviour happens?

**Comment by Ovenoboyo** [comment]
You're right. This does indeed happen with flatpak. I'll have a look into this

**Comment by Klavrin** [comment]
Looking forward to it. Thanks

**Comment by Ovenoboyo** [comment]
This should fix the issue for flatpak https://github.com/flathub/app.moosync.moosync/commit/dd7a055ea866da0f92188654edf8f369561751f4
